### ISSUE TITLE
Label overwrite border when on 0 position

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/material-ui-swing#101]
a) normal
![](https://user-images.githubusercontent.com/59824651/72506985-4b914f80-3843-11ea-90ef-c477fc4443fd.png)
b) material
![](https://user-images.githubusercontent.com/59824651/72507041-68c61e00-3843-11ea-8d49-f917c4c98fdd.png)

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys, good day.

I'm trying to reproduce this problem, but I don't see the problem with this code

```
package integration.gui.mock;

import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.JMarsDarkTheme;
import mdlaf.utils.MaterialColors;

import javax.swing.*;
import java.awt.*;

public class Issue101Frame extends JFrame {

    static {
        try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new JMarsDarkTheme()));
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }

    private JPanel panel;

    public void initComponent(){
        panel = new JPanel();
        panel.setBorder(BorderFactory.createLineBorder(MaterialColors.AMBER_500));
        JLabel label = new JLabel("Some text");
        label.setBorder(BorderFactory.createLineBorder(MaterialColors.COSMO_GREEN));
        panel.add(label);

        this.setContentPane(panel);

        this.setLocationRelativeTo(null);
        this.setSize(500, 500);
        this.setVisible(true);
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                Issue101Frame frame = new Issue101Frame();
                frame.initComponent();
            }
        });
    }
}
```

I can see this effect

![Selection_001](https://user-images.githubusercontent.com/17150045/72610186-0cd4c580-3927-11ea-81ff-eff98d02fa19.png)

**Comment by jarek-insys** [comment]
Hi Vincent @vincenzopalazzo,

Of course you will not eproduce it with that code.
Problem is when label start at position 0 so x=0  or y=0
but text is printed with alignment
and my example code was 

import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public class LabelExample extends JFrame {

   private static final long serialVersionUID = 1L;
   static {
      try {
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.MaterialOceanicTheme()));
         UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialLiteTheme()));
         // UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new
         // mdlaf.themes.JMarsDarkTheme()));
         UIManager.put("Button.mouseHoverEnable", false); // Because the test are more difficulte with effect mouse
                                                          // hover
         JDialog.setDefaultLookAndFeelDecorated(true);
         JFrame.setDefaultLookAndFeelDecorated(false); // not support yet

      } catch (UnsupportedLookAndFeelException e) {
         e.printStackTrace();
      }
   }
   public static void main(String args[]) {
      LabelExample frame = new LabelExample();
      frame.setTitle("Label issue example");
      frame.setDefaultCloseOperation(EXIT_ON_CLOSE);
      frame.getContentPane().setLayout(null);
      JPanel p = new JPanel(null);
      frame.getContentPane().add(p, null);
      p.setBounds(50, 50, 200, 200);
      p.setBorder(BorderFactory.createEtchedBorder());
      JLabel l = new JLabel("Some text", SwingConstants.CENTER);
      p.add(l, null);
      l.setBounds(0, 50, 200, 21);
      frame.setBounds(0, 0, 300, 300);
      frame.setVisible(true);
   }
}

**Comment by vincenzopalazzo** [comment]
I found the problem @jarek-insys, this is a particular of Swing, I would introduce it with an example:

## Introduction

Material-UI-Swing uses the propriety `UIManager.put("Label.opaque", true);` by default, and with this propriety set to true you can see this effect 

![](https://user-images.githubusercontent.com/59824651/72507041-68c61e00-3843-11ea-8d49-f917c4c98fdd.png)

if you set inside your code  `l.setOpaque(false);` you can see this effect

![Selection_002](https://user-images.githubusercontent.com/17150045/72614980-e36e6680-3933-11ea-9e3e-423687f4fe60.png)

## Conclusion and Solution
to conclude, in version 1.1.1 official (coming soon) the propriety will do configure with MaterialTheming and it by default will false.

At this moment this issue is a part of the documentation of material-ui-swung, thanks for your time

**Comment by vincenzopalazzo** [comment]
This issue was considered a bug for this answer https://stackoverflow.com/a/2452381/10854225

The call to label.setOpaque and Label.opaque was deprecated in future version 1.1.1 and it will be removed in version 1.2 (the release of version 1.2 doesn't is scheduled yet)

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
