### ISSUE TITLE
Table header no headers split

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/material-ui-swing#103]
a) normal
![](https://user-images.githubusercontent.com/59824651/72507594-77610500-3844-11ea-88c9-7f0b98ae43f0.png)

![](https://user-images.githubusercontent.com/59824651/72507820-ecccd580-3844-11ea-8613-e0a0a4e9e601.png)

b) material
![](https://user-images.githubusercontent.com/59824651/72508227-9b711600-3845-11ea-965d-2a709ed1b6aa.png)

**Comment by vincenzopalazzo** [comment]
Hi @jarek-insys,

Does this screen resolve your problem?


![Selection_028](https://user-images.githubusercontent.com/17150045/74030928-8a34a880-49b0-11ea-80f6-5a62ddaa07cc.png)

**Comment by jarek-insys** [comment]
Hi @vincenzopalazzo,

Yes looks ok

**Comment by vincenzopalazzo** [comment]
Done in material-ui-swing-1.1.1-rc1

If you aren't able to see the grid, use this propriety inside the UIManager 

UIManager.put("TableHeader.gridColor", COLOR);

Or create a your personal theme, guide TO DO
