### ISSUE TITLE
TextField - Disabled State Indicator

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#105]
Vincent,
do we have an effect in the latest version of material lib to indicate that a Textfield is disabled for input?

This image shows one of my screens in a "disabled" state, where text labels are visibly disabled while input Textfields are also disabled, but **visibly** enabled, although user cannot type into fields. This is confusing to a user as user **thinks** he **can** type into fields.

![jmars5-filter-disabled](https://user-images.githubusercontent.com/49419742/73244331-eb65ac00-4166-11ea-8b11-380846976f32.jpg)

This image shows the same screen using Metal L&F. Can we achieve Textfields's "disability" with material?

![jmars4-filter-disabled](https://user-images.githubusercontent.com/49419742/73244645-a9893580-4167-11ea-8277-f6482921d855.jpg)

**Comment by vincenzopalazzo** [comment]
Hi Zoya,

The TextComponent how TextField and PasswordField doesn't have the possibility to paint of the disabled state for the moment.

I will try to support this inside the official version 1.1.1 and for the moment I have a solution and it looks like

Active State

![Selection_019](https://user-images.githubusercontent.com/17150045/73555494-03cb1480-444e-11ea-8566-2d299d7d0465.png)

Disabled State

![Selection_020](https://user-images.githubusercontent.com/17150045/73555549-20ffe300-444e-11ea-94be-5d097b2b78f0.png)


the style following the line guide of google

![](https://storage.googleapis.com/spec-host/mio-staging%2Fmio-components%2F1579302979877%2Fassets%2F1TKi-wOcOI4c_XQswgLFfHS1078d1wAzJ%2Ftextfields-filled-states.png)

Inside the configuration, I added the new constant, like

```
 UIManager.put("TextField.disabledBackground", theme.getDisabledBackgroudnTextField());
 UIManager.put("TextField.disabledForeground", theme.getDisabledForegroundTextField());
UIManager.put("PasswordField.disabledBackground", theme.getDisabledBackgroudnTextField()); 
UIManager.put("PasswordField.disabledForeground", theme.getDisabledForegroundTextField());
```

**Comment by zanderson9** [comment]
Vincent, thank you for the documentation.

Following your guide, I was able to achieve a desired "disabled" look for JMARS textfields.

Thank you.

![JMARS5-Filters-Disabled](https://user-images.githubusercontent.com/49419742/73572036-141ec780-442d-11ea-8c51-b00b1a05933c.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I think you have lost something inside your configuration because the underline effect when the component is disabled it does paint with the same color disableBackground.
Inside your screen the underline effect is distinguishable.

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
