### ISSUE TITLE
Need to be Able to Change Button's OnHover Color

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#106]
Is it possible to add a feature to MaterialButtonUI to allow the client's code to change **mouseHover** color property at runtime, via installUI()?

For example, per the main JMARS theme, **mouseHover** is "cyan" and it works well for the pushbuttons. But for certain icon buttons we want to be able to set a different mouseHover color, for example, "grey" for  ---> and <--- similar to like browser has it for its toolbar navigation buttons (image attached).

![Hover](https://user-images.githubusercontent.com/49419742/73492359-c42cfb80-436d-11ea-9e84-4208e23bcafb.png)

**Comment by vincenzopalazzo** [comment]
HI @Zoya,

You want to add personal color to MouseHover only once as an example you want to add personal color mouse hover only on some component, or you can choose the color of MouseHover as an example with color-chooser inside the client application?

**Comment by zanderson9** [comment]
Hi Vincent,
to answer your question for more detail: I want to be able to add personal color "**once**", only on some component. Similar to how I can set a button's background color "once", only on certain buttons, using installUI() method.
For example, for selective components I'd like to be able to do the following:

_super.installUI();
mouseHoverEnable = true;
mouseHoverColor = Color.GRAY;_

**Comment by vincenzopalazzo** [comment]
Hi Zoya,

You can set the personal color to MouseHover inside your method installUI(), you can use this code:

```
private static class MyArrowButtonUI extends MaterialButtonUI{

        @Override
        public void installUI(JComponent c) {
            mouseHoverEnabled = false;
            super.installUI(c);
            if (mouseHoverEnabled != null) {
                JButton b = (JButton) button;
                if (!b.isDefaultButton()) {
                    button.addMouseListener(MaterialUIMovement.getMovement(button, MaterialColors.COSMO_DARK_GRAY));
                }
            }
        }
```

## Analisis of code

`mouseHoverEnabled = false;`

Disabled the MouseHover of the library.

      if (mouseHoverEnabled != null) {
                JButton b = (JButton) button;
                if (!b.isDefaultButton()) {
                    button.addMouseListener(MaterialUIMovement.getMovement(button, MaterialColors.COSMO_DARK_GRAY));
                }
            }

Set the personal color to the MouseHover event.

To usually the DefaultButton are, all the same, so for the moment you can not set the personal color to the Default button.

**Comment by zanderson9** [comment]
Hello Vincent,
 I tried to implement this code for the Location Manager (navigation) in JMARS.
Here is my code in class edu.asu.jmars.LocationManager.java, for the component called **PlaceButton**:

_**@Override
		public void installUI(JComponent c) {
			mouseHoverEnabled = false;
			super.installUI(c);
			super.background = ((ThemeButton) GUITheme.get("button")).getThemebackground();
			super.disabledBackground = ((ThemeButton) GUITheme.get("button")).getDisabledback();			
			super.defaultBackground = ((ThemeButton) GUITheme.get("button")).getThemebackground();			
			 if (mouseHoverEnabled != null) {
	                JButton b = (JButton) button;
	                if (!b.isDefaultButton()) {
	                    button.addMouseListener(MaterialUIMovement.getMovement(button, Color.PINK));
	                }
	            }			
		}**_

So there seem to be a bug: the Hover color "paints over" the button when it becomes disabled. In other words, the visual "disabled" effect gets overwritten by Hover color. 
Here are the images:

- this is the desired look for when the button is in the **disabled** state:

![CorrectDisabledLook](https://user-images.githubusercontent.com/49419742/73703053-f4e19d80-46ab-11ea-8769-b6b5d39d6b6d.png)


But the actual look with the above code when button becomes "disabled" after the final click, is this:

![HoverRemains](https://user-images.githubusercontent.com/49419742/73703107-18a4e380-46ac-11ea-88e8-229151719946.png)

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
