### ISSUE TITLE
The mouse hover effect work wrong with disabled action on click

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/material-ui-swing#107]
The mouse hovers effect work wrong with disabled action on click, an example:

If I have a button and it went disabled after the click, the color background change in the mouse over color and the effect is described in this issue: https://github.com/vincenzopalazzo/material-ui-swing/issues/106#issuecomment-581688273

The effect mouse hover on the button worked wrong when the button has the disabled action in your life cycle.

**Comment by zanderson9** [comment]
The issue persists with pre-release2.jar.

I left a comment on Slack about it.

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
