### ISSUE TITLE
Library version 1.1.1 - Window "X" Not Visible

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#108]
With the latest release, 1.1.1, we have noticed that a dialog's exit button, "X", is no longer visible in the upper-right corner.

It was visible with the previous library releases, including 1.0.9.

What had changed?

**before - with 1.0.9**

![YesX](https://user-images.githubusercontent.com/49419742/73809422-7c084180-4790-11ea-8e7b-3bb3b347d796.png)

**now - with 1.1.1**

![NoX](https://user-images.githubusercontent.com/49419742/73809445-8b878a80-4790-11ea-8c09-d9ef42ef7ddb.png)

**Comment by vincenzopalazzo** [comment]
HI @zanderson9,

I think that inside the JMars configuration lost the following configuration:

```
UIManager.put("InternalFrame.closeIcon", MaterialImageFactory.getInstance().getImage(MaterialImageFactory.CLOSE_WINDOWS_BLACK));
```

I'm working on TitlePane and in the version 1.1.1 the icons can be configuring with MatherialTheme

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
