### ISSUE TITLE
Library version 1.1.1 - Tabs Don't Wrap When Window is Resized to Smaller Size

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#109]
When user makes a window with Tabs smaller in width, by dragging any of the corners,  the tabs do not wrap and are not properly displayed in a smaller sized window. I tried to set JTabbedPane scroll policy to WRAP or SCROLL, but none took effect under material lib.
However, in Metal L&F tabs wrap or scroll properly.

How can this be fixed?

**Normal view with TABS**

![Tabs-FullView](https://user-images.githubusercontent.com/49419742/73809709-4d3e9b00-4791-11ea-89d0-0a7ab59baad3.png)

**Same window when the width is reduced**

![LostTab](https://user-images.githubusercontent.com/49419742/73809734-60516b00-4791-11ea-839a-bbfeb013d65b.png)

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
