### ISSUE TITLE
Customizing Non-Icon JButton 

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#111]
Hi Vincent,

I have a custom button (attached) which has multiple components added to it, JLables mostly, but no Icons.
I want to customize this button same way we customize Icon buttons. So with IconButtonUI I am able to achieve many of the desired effects, except I cannot remove the border. You can see from the attached image, the cyan border around this  "long" button is showing.
Is it possible to tell the library code via **_super.borderEnable=false_** to **not** draw a border for non-icon button?

![CustomButton](https://user-images.githubusercontent.com/49419742/74377558-605cf680-4da1-11ea-88bf-27c36cc9e8b7.png)

**Comment by vincenzopalazzo** [comment]
HI @zanderson9, 

Do you have the mock of the desired effect?

**Comment by zanderson9** [comment]
Yes, the desired effect is attached. I

In this image, each entry in the SEARCH LAYERS tab, with +, map label, "i" and Name,  is a **JButton**, with several labels added to it, and **no** icons. So to have the desired look with "no border" I did a trick, by adding "invisible" icon to it. That way, the material library "understands" it is Icon button and **allows** it to have no border. Good. But for future development, I would like to avoid doing the "trick" and be able to customize a button even if it is **not** Icon button.


![Button-NoBorder](https://user-images.githubusercontent.com/49419742/74387043-ca32cb80-4db4-11ea-8b5b-144003bdaf43.png)

**Comment by vincenzopalazzo** [comment]
I understand Zoya, tomorrow I will start to work to add this possibility.

Thanks.

**Comment by vincenzopalazzo** [comment]
HI Zoya, 

If I understand your request, you can disable all border to button with this propriety ` super.borderEnabled = false; `

You should add this value to the propriety after the method super.installUI in  your personal component.

The effect is like the following.

- super.borderEnabled = true

![Selection_030](https://user-images.githubusercontent.com/17150045/74431015-61a02900-4e5e-11ea-85ae-b96aea7eac60.png)

- super.borderEnabled = false

![Selection_031](https://user-images.githubusercontent.com/17150045/74431024-68c73700-4e5e-11ea-98b0-c5cf3090c7fa.png)


The propriety is used here inside the library

https://github.com/vincenzopalazzo/material-ui-swing/blob/b4b55df1e88402d9470ad167db6111b18c199ea5/src/main/java/mdlaf/components/button/MaterialButtonUI.java#L189-L191

This resolved your problem?

**Comment by zanderson9** [comment]
Vincent, Yes, this setting "super.borderEnabled = false;" resolved the problem for non-icon button.
Thank you.

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
