### ISSUE TITLE
Tabbed Pane - Disabled Tab Color Setting

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#113]
Hello Vincent,

I was not able to change color for a disabled TAB (see FAVORITES tab, next to BROWSE LAYERS in the attached image). If in the code we just set TAB. enabled(false), then with our JMARS dark theme that disabled tab is almost invisible. Meanwhile, setting _**UIManager.put("TabbedPane.disableContentAreaColor", Color.GRAY);**_ 
did not take effect...
How to customize the disabled TAB color?

![DisabledTab](https://user-images.githubusercontent.com/49419742/74389700-45e44680-4dbc-11ea-959b-5f911b50644c.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Thanks for this issue, by default JTabbedPane with BasicTabbedPaneUI, don't support the disabled text color but utilized the background.

I will add the possibility to add the disabled text color with this new propriety inside the next version of the library (1.1.1)

`UIManager.put("TabbedPane.disabledForeground", COLOR);`

This is the actual effect

![Selection_032](https://user-images.githubusercontent.com/17150045/74434069-efc9de80-4e61-11ea-87e5-c1dc0ee86044.png)


this propriety with material theming is set like this code

`UIManager.put("TabbedPane.disabledForeground", theme.getDisableTextColor());`

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
