### ISSUE TITLE
Button Tabbing - Visual Effect

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#120]
When tabbing from a "default" button to a non-default button, the visual effect is not obvious, i.e. the default button stays as-is, no change in back, while secondary button, with focus on it, also not displaying a change.

For example, in the JMARS Exit dialog, "No" is the default (cyan back), "Yes" is secondary (no back). When I tab from No to Yes, "No" remains with cyan back and Yes, now in focus, remains with no back.  So it is visually not clear that Yes is now in focus. 

Example:

No is Default

![Buttons-Tabs](https://user-images.githubusercontent.com/49419742/76810366-05a52900-67ab-11ea-8328-57db3a50b619.JPG)

But now I tabbed from it to Yes... and it is not obvious...

![ExitJMARS](https://user-images.githubusercontent.com/49419742/76810378-15247200-67ab-11ea-8f72-f6ad30d8d78d.png)

So this issue is basically asking us to implement buttons' visual effects, default and secondary, according to this design, such that both secondary and primary buttons visually respond to On Hover/Focus/**Tab**. Can we achieve this?

![Button States](https://user-images.githubusercontent.com/49419742/76810931-148cdb00-67ad-11ea-952d-904489b2705b.png)

**Comment by vincenzopalazzo** [comment]
Done material-ui-swing-1.1.1-rc1
