### ISSUE TITLE
Task Pane - Title Bar text Color Does not Observe Theme Settings

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#123]
It was noticed in library version 1.1.1_01 or 1.1.1_02 -
Task Pane title was able to be set to a theme's color via UIManager settings when working with library versions prior to 1.1.1_01.  But 1.1.1_01 switched color to Blue without observing the custom theme's settings.

White foreground in TaskPane's Title (prior to ver 1.1.1_01)

![TaskPane-Title-correct](https://user-images.githubusercontent.com/49419742/77270183-5e236d00-6c68-11ea-86b6-c803b696b025.JPG)

Provided all the same custom settings, Title is now Blue without observing theme's colors in 1.1.1_01 and 1.1.1_02

![TaskPane-Title](https://user-images.githubusercontent.com/49419742/77270206-77c4b480-6c68-11ea-8ab9-a8217ad8a36c.JPG)

**Comment by vincenzopalazzo** [comment]
Fixed in material-ui-swing-1.1.1-rc1
