### ISSUE TITLE
Dialog Title Bar - Title  is Cut Off in 1.1.1_02

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#124]
![Dialog-cutoff2](https://user-images.githubusercontent.com/49419742/77270295-be1a1380-6c68-11ea-9547-8bc673b99110.JPG)

![Dialog-cutoff](https://user-images.githubusercontent.com/49419742/77270305-c5d9b800-6c68-11ea-964c-fb54cdd355f5.JPG)

**Comment by vincenzopalazzo** [comment]
Fixed inside material-ui-swing-1.1.1-rc1
