### ISSUE TITLE
Button Loses Border - ver 1.1.1_01

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#125]
Noticed that with ver 1.1.1_0.1, in certain scenarios with Table,  OK button loses its border on 2nd or 3rd invocation.

Example,

1. start JMARS
2. bring up Custom Shapes table
3. right-click on Table header to bring up Columns popup window with Columns table in it
4. Observe, OK button has a border

![Table-Buttons-good](https://user-images.githubusercontent.com/49419742/77602081-c1600a00-6ec9-11ea-826f-0d27921ff9cf.JPG)

5. click OK close window
6. Repeat step 4 to open it again.
7. Observe, button OK has no border

![Table-Button-lost](https://user-images.githubusercontent.com/49419742/77602132-df2d6f00-6ec9-11ea-81c9-323708ccc3ee.JPG)

but if to do any action inside Columns table, for ex, check/uncheck boxes, then border to this button reappears...

8. Or while Columns table is open, click on HIDE ALL or SHOW ALL buttons - on click border disappears

![Buttons-noborder](https://user-images.githubusercontent.com/49419742/77602362-84484780-6eca-11ea-90af-49dbb48d5c18.JPG)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

What is "bring up Custom Shapes table" in JMars?

**Comment by vincenzopalazzo** [comment]
The bug was present whey the `button.setFocusable(false);`

**Comment by vincenzopalazzo** [comment]
Fixed inside material-ui-swing-1.1.1-rc1
