### ISSUE TITLE
Secondary Buttons Retain "Hover" Look After Being Clicked - 1.1.1_01

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#126]
Observed the following issue in 1.1.1_01

1. Bring up a dialog, for ex File Load Session
2. it has 2 buttons - primary "LOAD" and secondary "CANCEL"

![Buttons - State-1](https://user-images.githubusercontent.com/49419742/77602614-223c1200-6ecb-11ea-8af9-201239915aec.JPG)

3. Click CANCEL (upon click hover effect) - dialog closed

4. Reopen same dialog

5. Observe - CANCEL has Hover effect if it was clicked prior, and does not restore to its expected look in Step 1

![Buttons-state2](https://user-images.githubusercontent.com/49419742/77602702-57486480-6ecb-11ea-9b4b-5a40a46045ea.JPG)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

When you click on "CANCEL" button, you have hidden the FileChooser, right? have you hidden file chooser and don't cancel it?

**Comment by vincenzopalazzo** [comment]
Button Loses Border - ver 1.1.1_01
