### ISSUE TITLE
Missing DarkStackOverflowTheme in build?

### ISSUE THREAD

**Issue by mikera** [vincenzopalazzo/material-ui-swing#132]
The DemoGUITest appears to reference a missing class in the line:

```java
UIManager.setLookAndFeel(new MaterialLookAndFeel(new DarkStackOverflowTheme()));
```

This is currently breaking the build. Suggest either removing this theme, or adding it in to the material-ui-swing repo?

**Comment by vincenzopalazzo** [comment]
Hi @mikera,

I'm developening this theme and don't exist inside the library. I make the commint to remove it.

Thanks so much.

**Comment by mikera** [comment]
OK thanks! Will try the latest development version!
