### ISSUE TITLE
Textbox collapses when Main Window is Resized (width reduced)

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#134]
Using the latest version, 1.1.1_0.4, it is observed that the textbox for Lat, Lon in JMARS Toolbar collapses when main window's width is reduced.

Here is the regular textbox with regular size frame

![fullsizetextbox](https://user-images.githubusercontent.com/49419742/80675261-e4518100-8a68-11ea-9703-c3bfad378bcc.png)

and here it is collapsed as window's width reduced by dragging window's corner

![textboxcollapsed](https://user-images.githubusercontent.com/49419742/80675357-1a8f0080-8a69-11ea-8f46-7c05c0d019ab.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Can you reproduce this problem? Inside the Material text demo, there is a lot of text field and I don't see this problem. In addition, the last modified code was 4 months ago.

Another util information, material-ui-swing does not use never the setSize() or any propriety to change the dimension.

**Comment by zanderson9** [comment]
Hi Vincent,

yes, I can reproduce this problem repeatedly on Windows, or Mac OS X. I don't recall seeing this issue with older material lib versions?.. but we just started to notice it now, maybe starting from 1.1.1_0.3

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Can you post your demo to reproduce the problem?

>yes, I can reproduce this problem repeatedly on Windows, or Mac OS X. I don't recall seeing this issue with older material lib versions?.. but we just started to notice it now, maybe starting from 1.1.1_0.3

I think no because you should see the problem with all JTextBox

**Comment by zanderson9** [comment]
you are correct, I do not see this collapse happen to other textbooks when their containing window is resized... 
nor did I see this problem for the Lat Lon window before, but just starting recently.

If you are certain this is not a library issue, then Close this issue. I will continue to research on JMARS end, knowing you are certain this is not library.

**Comment by vincenzopalazzo** [comment]
I make a rapid test inside the my local version JMars 08/02/2020, the problem persist.

Inside this version should be present an old material version, like 1.1.1_0.1.

You should see the problem before because JMars will start with a full screen and not like the last version of the library.

I left open this issue until you will found the problem inside the client code.

I hope I make good information.

**Comment by vincenzopalazzo** [comment]
Closed because this is a client bug.
