### ISSUE TITLE
Glitched JToggleButtons when adding them dynamically to a scrollpanel

### ISSUE THREAD

**Issue by Vodes** [vincenzopalazzo/material-ui-swing#136]
Font formatting works in rc2 but the buttons themselves break

1.1.1-rc2:
![wBjllbwpoVWr0ry](https://user-images.githubusercontent.com/48185123/81593207-645bdd00-93bf-11ea-958e-08150e7a4c4d.png)

1.1.1-rc1:
![645oPsqtzz52rTG](https://user-images.githubusercontent.com/48185123/81593224-6cb41800-93bf-11ea-8067-17d349cd4c3b.png)

[The code i use to add the buttons](https://del.dog/ryckepedyl.txt)

**Comment by vincenzopalazzo** [comment]
Hi @Vodes,

Thanks to test the version rc2 of library.

I found this bug in this weekend and I resolved it in this [commit](https://github.com/vincenzopalazzo/material-ui-swing/commit/cc7d10c3b6ab593b9b98210510ba4cf8e86d741b) on developing branch.

if you want to test and resolve this bug with the last changes you can compile the new version and test the version rc3

You can compile with the version with this command in the root dir of project

```
./gradlew jar
```

When gradle finish you can find the new jar in `build/libs` dir

Let me know if you have any questions or you are interested to restore the old icon (png) with MaterialTheming.

**Comment by vincenzopalazzo** [comment]
Hi @Vodes,

Another question about the font.

You are running the your app with JDK 8, right?

In your console when the app startup, you can see an integer number in the console, can you say me what is this number in your console?

**Comment by Vodes** [comment]
Im using Verdana 13 (Bold) on those pictures. The Integers are 96.

I'll look forward to the next release ^^

**Comment by vincenzopalazzo** [comment]
Hi @Vodes.

Thanks for your answer.

>I'll look forward to the next release ^^

it is coming :)

**Comment by vincenzopalazzo** [comment]
Fixed into https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-rc3

Thank you.
