### ISSUE TITLE
Add Tickmark Color Setting to JSlider

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#143]
Is it possible to add "tickmark" color for JSlider as a setting via UIManager to customize tick color per client theme?

without such option, tick colors are painted with a default color which may be invisible in a c custom theme...

<img width="494" alt="slider-ticks" src="https://user-images.githubusercontent.com/49419742/87610106-3b0a4680-c6b9-11ea-86ab-42f684e58d3a.png">

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This is a good question, and at the moment I don't know the answer, I'm not the developer of Material Slider and I don't know the code very well but I can start to work on this to give you an answer.

**Comment by zanderson9** [comment]
Hi Vincent,

thank you for your reply.

I looked into the code on MaterialSliderUI and the class that it extends, BasicSliderUI. By reading that code I noticed that there is method in BasicSliderUI, paintTicks, which pulls color from UIManager("Slider.tickColor");
So I just added that setting on my end and specified the color as per the theme. And it worked the magic... As you can see from attached, the ticks are now white for this theme and are visible.

No action is needed on your end, we can close this issue.

<img width="362" alt="slider-ticks" src="https://user-images.githubusercontent.com/49419742/87640310-60b83f80-c6fb-11ea-9b14-16c33b607bd3.png">

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Thanks for this research inside the java code, I will add the support of this variable inside MaterialTheme.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, I'm closing this issue because now the `tickColor` is supported by MaterialTheme inside the master branch with this commit https://github.com/vincenzopalazzo/material-ui-swing/commit/5447eae829d87cc0819aa1d96184e6aba7568873
