### ISSUE TITLE
Cannnot set SetEnable(false) of the jbutton

### ISSUE THREAD

**Issue by AlessandroPasqua** [vincenzopalazzo/material-ui-swing#178]
![imm 1](https://user-images.githubusercontent.com/62487636/155528309-a555ceae-776b-4fcf-847e-61349697ebfa.jpg)
![IMM 2](https://user-images.githubusercontent.com/62487636/155528314-e8ced149-ef3c-487c-b092-f2de02137191.jpg)
![IMM 3](https://user-images.githubusercontent.com/62487636/155528319-efe05966-4f4d-486a-b0d5-8f17f8517e97.jpg)
![initComponent](https://user-images.githubusercontent.com/62487636/155528565-bcc5f5af-6251-4146-8257-d8081605fa64.jpg)

**Comment by vincenzopalazzo** [comment]
Solved by call SetEnable after the init action!

Thanks!
