### ISSUE TITLE
JDialog - Text in Title Pane is always "Disabled"

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#187]
I'm using the latest release of the material lib, 1.1.3-rc2. 
Noticed that a title text in JDialog's title pane is always displayed in a "**disabled**" state, even if JDialog is _active_ and _in focus_.

Couple examples are attached.

My setting in the theme's configuration is **JDialog.setDefaultLookAndFeelDecorated(true)**, so that we get a "flat" look and feel and a custom "close" button in its title bar. With this setting, enabled/disabled text doesn't work but if to set it to "false", then enabled/disabled text does work. More details below:

I debugged this issue and found that the call to "_paintComponent_" in **MaterialTitlePane** class has a conditional logic to check for window's active or inactive status. Then, based on that status, it chooses text colors for the title, accordingly. So the "window.isActive()" returns **false** when JDialog is shown or when user clicks inside it, when in fact it should be returning **true**. Furthermore, when setting **_JDialog.setDefaultLookAndFeelDecorated(false)_** then active/inactive status for the same JDialog functions correctly and the title text gets enabled or disabled accurately.

Does this give any hint as to why the title remains inactive with _**JDialog.setDefaultLookAndFeelDecorated(true)**_ when JDialog is active?

Thank you.

![dlg1](https://user-images.githubusercontent.com/49419742/184471215-2626917a-4ffa-4e99-b332-190ea091d0d1.jpg)
![dlg2](https://user-images.githubusercontent.com/49419742/184471219-78c5bff1-0b2d-4f6f-b1a4-acb336700d8d.jpg)

**Comment by vincenzopalazzo** [comment]
Mh!

Looks like it contains the default color, maybe your theme conf does not override some of these variable?

https://github.com/vincenzopalazzo/material-ui-swing/blob/master/src/main/java/mdlaf/MaterialLookAndFeel.java#L696-L749

**Comment by zanderson9** [comment]
Hi Vincent,

the configuration colors for title text being default is not a problem. The default color for inactive text is RGB(148,167,176) and the default color for active title text is RGB(84,110,122). There is a clear visual difference between them, as seen in this image.

![dlg3](https://user-images.githubusercontent.com/49419742/184511437-97b77bb7-5d93-4169-90a7-80e3b582ea93.jpg)

However, I followed your suggestion and set the theme colors explicitly, like so:
     
        UIManager.put("Material.activeCaption", Color.LIGHT_GRAY);
        UIManager.put("Material.activeCaptionText", Color.GREEN);
        UIManager.put("Material.inactiveCaption", Color.DARK_GRAY);
        UIManager.put("Material.inactiveCaptionText", Color.PINK);

These settings did not change the problem that I am seeing, as it continued to display only "disabled" text even when a window is "active", as seen in this image.

![dlg4](https://user-images.githubusercontent.com/49419742/184511567-2b272db4-3943-4203-8687-aaf958b9dca9.jpg)


I think the problem is this: because of the setting **_JDialog.setDefaultLookAndFeelDecorated(true)_**, we are informing SWING that the decoration will be provided by the current LookAndFeel and not the system's window manager. So SWING uses our "material" code for the decoration and title. Somewhere between the OS, SWING and "material" code the window is not properly registered and its active/inactive status is not captured accurately. Hence, "paintComponent" in MaterialTitlePane, lines 393-470, detects "false" for **window.isActive()** and paints title in disabled colors, be it default colors or a theme colors.

By comparison, we are setting Frame's **_setDefaultLookAndFeelDecorated_** to "**false**" which makes window manager take care of the window. With that, I observe that a frame's title for active or inactive status is painted accurately.

So to solve this, I think we need to understand why under **_setDefaultLookAndFeelDecorated(true)_** a window's focus or active status is not accurately reported back.

**Comment by vincenzopalazzo** [comment]
Thanks for this test Zoya!

Looks like there is a bug somewhere!

>So to solve this, I think we need to understand why under setDefaultLookAndFeelDecorated(true) a window's focus or active status is not accurately reported back.

Yes your description is perfect, are you using some particular JDK like Corretto? or in some particular os?

**Comment by zanderson9** [comment]
We continue to use Java 8, not Corretto. 
Our current JDK version with which we build JMARS is 1.8.0_144

**Comment by vincenzopalazzo** [comment]
Ok I put this on my todo list and see if we can push a solution in the next weeks

**Comment by zanderson9** [comment]
btw, I just tried to run JMARS with the previous version of material lib, 1.1.2, and the title text in JDialog gets enabled when the window is active/in-focus, and disabled when it is not. I have the same setting for JDialog.setDefaultLookAndFeelDecorated(true). 

So hopefully, because it worked under 1.1.2, it may give you a hint for the solution under 1.1.3.

![dlg5](https://user-images.githubusercontent.com/49419742/184516329-f87a949e-294e-4efe-83b1-2fe328a564fa.jpg)

**Comment by zanderson9** [comment]
Hi Vincent,

in reviewing this fix, I see that you modified MaterialLookAndFeel class with the settings for the "table". 

Is this the only change you plan to do to fix this bug?  

I think, the bug is deeper than just changing settings in the "table"... 

In trying this fix out, there is basically no change in the behavior on active/inactive.

To clarify, the text in the title pane is now displayed "always" enabled, even if the dialog looses focus and becomes inactive. This behavior is not consistent with how SWING works. If you try the same example with a JDialog under Metal or Nimbus, for example, you will notice that the title accurately "active" when JDialog window has focus/active, and title is "inactive" when window's focus is lost and window becomes inactive.
I don't see we have achieved that with this fix... In other words, the dialog window's active/inactive status is still not accurately reported to SWING, it is just that now the title is always shown "active", even if a window is inactive. Kind of the opposite of what it was before this fix, don't you think?

We can discuss in more detail over zoom, if you'd like.

**Comment by vincenzopalazzo** [comment]
>I don't see we have achieved that with this fix... In other words, the dialog window's active/inactive status is still not accurately reported to SWING, it is just that now the title is always shown "active", even if a window is inactive. Kind of the opposite of what it was before this fix, don't you think?

Yes, with a minor difference that in the material we do not have an inactive windows color change, debugging this change will require a lot of effort into debugging the state machine of the `MaterialTitlePane` because the bug was introduced in https://github.com/vincenzopalazzo/material-ui-swing/pull/177 a lot of time a go and unfortunately I do not understand why this bug came out only now :/, at the time was easy to catch if we noted.

In addition, the component still has some bugs around, like the JFrame Bug.

Why is the main functionality that you will lose with this code hack? I was thinking at least this will unlock you to fix your issue. or you are losing some important functionality that I need to be aware of?
