### ISSUE TITLE
JOptionPane - default button look

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#19]
When using JOptionPane in Swing and specifying Ok and Cancel buttons in its constructor, Swing UI renders the buttons such that it is **visually** **obvious** which button is "default", for example, by drawing a rectangle around default (OK) button in a background. 
Swing code example:
JOptionPane op =
			new JOptionPane(
				loginDialogContents,
				JOptionPane.PLAIN_MESSAGE,
				JOptionPane.OK_CANCEL_OPTION
				);

This visual indicator of a default button is lost when using material-ui-swing library. 
Same Option Pane displays both OK and Cancel the same way, user cannot tell which button is default.
Can the visual indicator of which button is default be restored with the "material" look under material-ui-swing?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This is code BasicOptionPane for create Button

```
private static class ButtonFactory {
        private String text;
        private int mnemonic;
        private Icon icon;
        private int minimumWidth = -1;

        ButtonFactory(String text, int mnemonic, Icon icon, int minimumWidth) {
            this.text = text;
            this.mnemonic = mnemonic;
            this.icon = icon;
            this.minimumWidth = minimumWidth;
        }

        JButton createButton() {
            JButton button;

            if (minimumWidth > 0) {
                button = new ConstrainedButton(text, minimumWidth);
            } else {
                button = new JButton(text);
            }
            if (icon != null) {
                button.setIcon(icon);
            }
            if (mnemonic != 0) {
                button.setMnemonic(mnemonic);
            }
            return button;
        }

        private static class ConstrainedButton extends JButton {
            int minimumWidth;

            ConstrainedButton(String text, int minimumWidth) {
                super(text);
                this.minimumWidth = minimumWidth;
            }

            public Dimension getMinimumSize() {
                Dimension min = super.getMinimumSize();
                min.width = Math.max(min.width, minimumWidth);
                return min;
            }

            public Dimension getPreferredSize() {
                Dimension pref = super.getPreferredSize();
                pref.width = Math.max(pref.width, minimumWidth);
                return pref;
            }
        }
    }
```

Into all code BasicOptionPaneUI isn't there a way to set the button style, a programming error for the part of the sun? bho who knows, but I can interfere in creating these buttons via a getButtons () method which returns an array of objects which are in turn buttons of a type that privately implements BasicOptionPaneUI.

Vistoc he always liked the effect of the primary and secondary button, I would like some time to think of an intelligent way to do it.

I leave you a reference to solve the problem momentarily and I hope I can find a good idea to do what you want

https://stackoverflow.com/questions/5877994/how-to-change-the-button-backgrounds-inside-joptionpane

**Comment by zanderson9** [comment]
yes, looks great!

**Comment by srcarter3** [comment]
Hi Vincent,
That screenshot you sent looks good with the default colors, but in our color scheme it doesn't look as good.
Maybe a thicker border would be good?  Also, us dark gray, not black?  And it doesn't seem to be completely aligned (closer to top and left, than bottom and right?).
I've attached a picture of how the default button looked in the old look and feel (with the default colors though), and how it looks in our new colors with your look and feel.
![newDefault](https://user-images.githubusercontent.com/21114460/55912426-7dc89f00-5b97-11e9-8a77-012c3f8af87a.png)
![oldDefault](https://user-images.githubusercontent.com/21114460/55912427-7dc89f00-5b97-11e9-9983-dd2d1e6a1d4d.png)

**Comment by vincenzopalazzo** [comment]
I will work on a smarter way to change colors

**Comment by lilili87222** [comment]
![joption](https://user-images.githubusercontent.com/2214998/55923810-bcaf3100-5c39-11e9-84c8-0a87068e05bd.png)
![joption2](https://user-images.githubusercontent.com/2214998/55923816-c0db4e80-5c39-11e9-92b9-5530871a3f27.png)

Is it possible the joption look like this

**Comment by lilili87222** [comment]
![joption3](https://user-images.githubusercontent.com/2214998/55923952-73131600-5c3a-11e9-99f3-7a6ba518b63f.png)
It may be better to remove the projection effect.

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, Ok I try to remove the projection effect and the icon will be removed in all the JOptionPane

**Comment by vincenzopalazzo** [comment]
HI @lilili87222, 
I can try this, but I wouldn't know if I could do it, and above all if it's a solution that does not give problems with possible configurations of the bread option, unfortunately from UI I can't interfere with anything other than with the events, look [here](https://stackoverflow.com/questions/17100587/setundecoratedtrue-to-a-jdialog-created-from-an-instance-of-joptionpane) 

No, I like the effect that joption bread has without edges, but you can set the border you like the most by editing UIManager, like this
`UIManager.put("OptionPane.border", YOUR_BORDER);`

**Comment by vincenzopalazzo** [comment]
hi @zanderson9, @srcarter3 

This bug is still present?

**Comment by srcarter3** [comment]
The default button looks the same as a button in Focus.  And it loses it's look as soon as a different button gains focus.   So yes, I would say this hasn't been addressed completely.

**Comment by vincenzopalazzo** [comment]
I will return to it

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, I had an idea for creating the Joption pane cool, 
I created a repo for swingx, the found into my repo, do we interfere with the construction of jXOption pane and add a constant that allows us to enable and disable the painting of JDialog?

it's just an idea, I have to study the code to see if it's possible and I have to see if I can fix an error in swingx core, but I can try when I have time, in fact, if you want to help me we can work together to create an OpenSwingX ahahah.

Sorry if I resume the speech, but I am native to java because in my course of study this language is dealt with swing technology and I dislike to know that I do not have the cool media available for my applications.

**Comment by vincenzopalazzo** [comment]
@lilili87222, I tried to follow your advice with the JDialog look, I am happy is you send me the example for the effect button where this is the focus

**Comment by lilili87222** [comment]
Swingx is another big project. As you said, keeping the skin properties of the material-ui-swing project, reducing the dependency as much as possible, and making the old project available, may be a good choice. Just like https://github.com/bulenkov/Darcula, a small jar can be used in various swing projects, which is great.
If some effects are not available through the skin interface, consider adding a branch project that expands on the basis of material-ui-swing to complement the hard-to-implement effects.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3 @zanderson9,

I added this change 

This is the [reference](https://github.com/vincenzopalazzo/material-ui-swing/issues/36) for the changes
I attend your feedback, thanks so much

**Comment by zanderson9** [comment]
Hi @vincenzopalazzo,
we just want to note that for future development the "Default" button look is still not quite nailed down. It is not critical for our upcoming _beta_ release of JMARS, but we would like to improve the look of "Default" button going forward, in the subsequent releases of the library.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This change is in the program but get a version personalizable with swing in more difficult.
The solution easy is to tie the look and fell the color, an example The Darcula theme has the button default blue but we do not to tie an color, so I will work for the good solution, but not in the version 1.0 because of the solution needed the tests.

Sorry.

I have a question for you, can you open an issue with the screenshot the tabbed pane component material so I add the new label if any person wants to collaborate with us that adding a new support component. Thanks

**Comment by zanderson9** [comment]
yes, I posted [New Issue](https://github.com/vincenzopalazzo/material-ui-swing/issues/50) for the tabbed pane component.
