### ISSUE TITLE
JOptionPane - default button Action

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#20]
When using JOptionPane in Swing and specifying OK and Cancel buttons in its constructor, Swing sets OK button as default, so that when user presses "Enter", the "Enter" key is linked to the OK button event.
JOptionPane op =
			new JOptionPane(
				loginDialogContents,
				JOptionPane.PLAIN_MESSAGE,
				JOptionPane.OK_CANCEL_OPTION
				);

This default mapping is lost when using material-ui-swing library: as Option Pane is displayed and user presses Enter, the OK button event is not triggered.
Can the default Enter-OK behavior be restored under material-ui-swing?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, 
Yout referer whit this code? on click the button ok? not returned input? 
```
 @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane op = new JOptionPane(null, JOptionPane.PLAIN_MESSAGE, JOptionPane.OK_CANCEL_OPTION);
                int input = JOptionPane.showConfirmDialog(null, "Do you like bacon?");
                System.out.println(input);
            } 
```

If I do not undestand, give me an code :) thanks

**Comment by zanderson9** [comment]
let us try it. Having a jar file will be great. No we do not use Maven, but Ant build script in Eclipse.
So we just take the jar from you and drop it into our library path...

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I added a jar for your test :)

Thanks for your help

**Comment by srcarter3** [comment]
Hi Vincent,

Your new jar worked for  JOptionPane.showConfirmDialog() with a JOptionPane.YES_NO_OPTION.  Yes was the default button and responded to an "Enter" press.
But it did not work for JOption pane built like this:
final JOptionPane op =
			new JOptionPane(
				loginDialogContents,
				JOptionPane.PLAIN_MESSAGE,
				JOptionPane.OK_CANCEL_OPTION
				);

The OK button used to respond to an "Enter" press (in the old look and feel).

Also, calling the following on a JDialog, no longer makes the button respond with "Enter":

getRootPane().setDefaultButton(addBtn);

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3, The problems are due only to shortcuts??

**Comment by srcarter3** [comment]
Hi Vincent,

Setting the default button like shown above, should set that button to respond to an Enter pressed.  It should not need to be set explicitly (at least it worked this way in the old look and feel).  Setting the default button changed the look, and had it respond to Enter.

**Comment by vincenzopalazzo** [comment]
@zanderson9 Perhaps the error is due to the shortcuts, I have to take a look calmly

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,
This problem can be solved if I can find a way to add the event to the action map, I hope to solve.
But at this time, time is not on my side, sorry if I can't fix this bug right away

**Comment by vincenzopalazzo** [comment]
hi @zanderson9, @srcarter3 

This bug is still present?

**Comment by srcarter3** [comment]
This works for us now. Thank you!

**Comment by vincenzopalazzo** [comment]
@srcarter3 I close the issue then, the issue aperde does not make me sleep at night :)
