### ISSUE TITLE
JList control - implementation request

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#22]
We started using material-ui-swing in our application and noticed that one of the controls, JList, didn't change its original Swing-like look (see attached screenshot), in terms of font, or background, or highlight.
Can JList control be included in material-ui-swing library?

![JList](https://user-images.githubusercontent.com/49419742/55767698-daf51100-5a2e-11e9-8994-3759cfe3aa56.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, 
Yes this control can be added to material-ui-swing, I just need some time, I want to take things slow to give an optimal solution

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Do you like this effect? 
![Selection_044](https://user-images.githubusercontent.com/17150045/55831036-832fd600-5b12-11e9-8534-669939186c15.png)

**Comment by zanderson9** [comment]
Looks good, we like it (with gray highlight).

**Comment by vincenzopalazzo** [comment]
I close the issue for problem resolution
