### ISSUE TITLE
Can't override PasswordField colors

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#25]
I'm not sure if this is an issue with the library or not, but I have not been able to override the JPasswordField properties, using the following code:

`		UIManager.put("PasswordField.background", theme.getHighlightBackgroundPrimary());
		UIManager.put("PasswordField.foreground", theme.getTextColor());
		UIManager.put("PasswordField.caretForeground", theme.getTextColor());
		UIManager.put("PasswordField.selectionForeground", theme.getTextColor());
		UIManager.put("PasswordField.inactiveForeground", theme.getTextColor());
		UIManager.put("PasswordField.selectionBackground", theme.getTooltipHighlight());
	`

This works for text fields, but the password field still has other colors set on it by default.  I'm wondering if maybe the PasswordFieldUI=mdlaf.components.password.MaterialPasswordFieldUI
call from the library, somehow prohibits changing the color properties?
![Screenshot-10](https://user-images.githubusercontent.com/21114460/55916356-013abe00-5ba1-11e9-82a2-ad06bbfa154c.png)

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,
The bug should no longer exist

**Comment by zanderson9** [comment]
verified with new **test** **jar** - looks good

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, good, the I closing a issue

**Comment by zanderson9** [comment]
@vincenzopalazzo, with the newest jar (April 23), the password field is "black" text again, and our settings of "white" are not able to override it.

![PWD-black](https://user-images.githubusercontent.com/49419742/56622048-75368680-65e3-11e9-9315-8e41c693a014.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, Sorry for this problem, in the new version the component JPasswordFieldUI is was complete re-writing, now the bug is fixed

[The version fixed](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0_Beta) and you find the jar also into libs dir of the project
