### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by vincenzopalazzo** [vincenzopalazzo/material-ui-swing#28]
Hi @atarw,
I was contacted by a Arizona State University (ASU), because they are using our work (sorry if I call it ours) for a https://jmars.mars.asu.edu/ project, they have opened some issues and I'm starting to work on it, but I don't like it because I'm only working on this project and I would like to ask you if you want to give me a hand, I see it as a great opportunity for growth for your look and feel, we can fix bugs eg and they are not very comforting, you are already a collaborator but I wanted to tell you in person why in my country (Italy) mpm there is the idea of working as a Team because envy reigns supreme and instead I love working as a Team because it makes one believe from the professional point of view faster, and who knows one day I will offer you a coffee ahahha but first I have to correct my English hahahha.

I hope you enjoyed this message and I hope you will work with me

**Comment by atarw** [comment]
Wow that is amazing news! I would be glad to work with you on this project and have that coffee with you :)

I'm aware I have not been very active for the past few months and I'm sorry that you were the only one working on this project, I do plan on being more active soon.

Just to let you know though, I will not be able to work on the project from mid-May to mid-August or so because of an internship. The contract I signed says that if I work on any outside projects during the internship the project may become the property of the company, which I don't want to happen.

For the next month or so I will be working hard to fix any bugs so that the project is stable over the summer.

Just wanted to end off and thank you for your help once again as this project definitely wouldn't be what it is today without you!

**Comment by vincenzopalazzo** [comment]
@atarw,
Thanks so much, Thank you,
Don't worry, I just wanted to know if I could count on your help, because programming in pairs is always better.

I will try to complete the site for donations where you will then add your references :)

In addition, even I, from the beginning of March, will no longer be very active because I will have to prepare the last two exams of the three-year course and then complete my thesis project, which is why I am very active in this period, because I want to arrive at a stable version by early April in fact I also fixed a milestone, we hope to be able to respect it.

I had some problems yesterday, where I provided some solutions in the day now I'm waiting for the results by tonight if I'm ok I align the project with yours.

Well now we are the ahhahahah material team :)

I will try to replace you during your internship :)

**Comment by atarw** [comment]
Just finished my final exam earlier today and I'm happy to say I am free! (at least for now)

I can now help work on this project, its been far too long haha

**Comment by vincenzopalazzo** [comment]
Hi @atarw, **I'm happy for your exam :)** 

I'm out this weekend and I have relatively little time due to my exam on May 10th, so I was working on small problems in carrying out the project.

But I tried to create a milestone for the end of May, we hope to respect it, I tell you the problems I am experiencing.

- Restyling at JTabbledPane, I want to add an effect like [this](https://github.com/vincenzopalazzo/material-ui-swing/issues/30)
- Try to improve the resize actions when the JDialog is not painted
- Support not painted JFrame
- Restoration of JTree
- Small issues that are opened 

it's hard but a good job is coming out, what do you think of my last update where I also created the pull request?

I'm also going through the problem of changing the color of the buttons when they change state but that is making it very difficult for me.

I only ask you if it's okay for you to update this [project](https://github.com/vincenzopalazzo/material-ui-swing/projects) when you start working on something so we avoid doing double work

**Comment by vincenzopalazzo** [comment]
Hi @atarw,

How are you?, I hope all go fine.

I have a question for you, I'm thinking to change the license from MIT to Creative Commons because I want to protect we work and if some Developer wants to change the code, they must add the reference to us.

What do you think, do you agree to add these features to the official 1.0 version?

**Comment by vincenzopalazzo** [comment]
Hello @atarw,

I'm working for respect this [milestone](https://github.com/vincenzopalazzo/material-ui-swing/milestone/1) and I think the version beta is available, but I'll test it again.
I think this milestone respect also your milestone, I'm referring to [this](https://github.com/atarw/material-ui-swing/milestone/1).

Now I want your help to select the change that you want in the version official (your version), I'm keeping a branch aligned with your version, where I started to change some time ago.
This branch has remained behind with my current beta version and I wanted your help to improve the code and make changes that look good to you for the official version.

What do you say? would you like to make this little effort with me?

If so, I created a slack channel where I am alone for now, if you want you can join the channel so we can have more direct communication.

I leave the namespace of the channel or you can leave me an email so I will add you as admin.

Channel **material-ui-swing.slack.com**

Thanks so much and good day

**Comment by atarw** [comment]
Yeah that sounds good to me. I won't really have much time to work on this project going forward other than small things here and there, but I want to get it to a non beta state before that happens.

I'll join the slack channel so we can discuss more :)
