### ISSUE TITLE
JList - keyboard navigation is lost

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#29]
The newly implemented Material JList control is not responding to user keyboard input, such as pressing "Up" or "Down" keys to scroll though the list. Only mouse scrolling is available, but keyboard should be too.
Please include "Up" - "Down" keyboard input to Material JList to allow scrolling through items.
![JList](https://user-images.githubusercontent.com/49419742/55990303-3526e980-5c5c-11e9-8529-2112bdfec7ac.png)

**Comment by vincenzopalazzo** [comment]
@zanderson9, Oh yes, I import this issue into my scheduler project. I hope to fix this issue By Sunday evening

**Comment by vincenzopalazzo** [comment]
@zanderson9 
This problem are resolved, I'm closing it
