### ISSUE TITLE
Updating JTabbedPane

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#30]
I was wondering if the look and feel could update the look of a JTabbedPane?  I feel like it still looks like it did previously.
I have attached a screenshot of what it looks like currently with the material library, and a mock up of what we would like to achieve.  (Some of the components are in different places, but please just focus on the tab appearances, thank you).
Do you think it's possible?  Do you like the look?
![Screenshot-12](https://user-images.githubusercontent.com/21114460/56062573-b2686200-5d21-11e9-83e8-6bb18944f11a.png)
![Screenshot-11](https://user-images.githubusercontent.com/21114460/56062574-b2686200-5d21-11e9-8693-cdabb9ab0f4f.png)

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

Yes this look is wonderful,  I have to think about how to do it, it will take some time

**Comment by zanderson9** [comment]
@srcarter3, good comment, thanks for bringing this up with Vincent.

**Comment by vincenzopalazzo** [comment]
This is the only version for tesh,

Do you like this effect?
![](https://media.giphy.com/media/2xPPcVC01sS7O9oi5P/giphy.gif)

**Comment by srcarter3** [comment]
Very cool.  Could the spacing be a little more?  Can the tabs be centered in the tabbed pane (instead of left-aligned).  Ex. if you have a very wide panel, can the tabs be centered? (like the screenshot above?)

**Comment by vincenzopalazzo** [comment]
Just to understand if I understood correctly, the spacing along the x axis is true?

**Comment by srcarter3** [comment]
Yes, that's what I'm referring to.

**Comment by vincenzopalazzo** [comment]
Now is ok? :)
![Selection_049](https://user-images.githubusercontent.com/17150045/56068532-7e238e80-5d7f-11e9-8697-5e6e24c58395.png)

**Comment by srcarter3** [comment]
Hmmm. I'm not sure I can tell the difference.
I'm mostly referring to the the tab alignment within the entire panel.
See the screenshots below.
![Screenshot-12](https://user-images.githubusercontent.com/21114460/56068795-06307680-5d35-11e9-8ff5-5c71a89e6543.png)
![Screenshot-11](https://user-images.githubusercontent.com/21114460/56068796-06307680-5d35-11e9-9467-653f8d1d5af7.png)

**Comment by vincenzopalazzo** [comment]
@srcarter3, For the position it takes a little more time, sorry

**Comment by srcarter3** [comment]
That's totally ok.  Don't feel like I'm rushing you.

**Comment by vincenzopalazzo** [comment]
Ok now I understand, you want there to be more space between one Tab and another, right? on this we will work and I will try to reproduce your mock because it is cool, now I make a commit to make some small changes, but above all this fix has to be revised from the point of view of the composting of the change state of the component

**Comment by srcarter3** [comment]
Yes, more space between each tab.
And, all tabs centered, not left-aligned.

Okay, that sounds good!  Thank you.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3 @zanderson9 ,

I added this change 

This is the [reference](https://github.com/vincenzopalazzo/material-ui-swing/issues/36) for the changes
I attend your feedback, thanks so much

**Comment by zanderson9** [comment]
Hello @vincenzopalazzo,
With the newest release of the library which implements centered tabs, we started to notice a **shift-left** of the tabs. Specifically, the shift to the left is noticeable when we add tabs, or "Dock", tabs to a TabbedPane.
I am attaching the document where I show various scenarios of adding tabs dynamically to a tabbed pane and how they shift. The document also shows, for comparison, how docking same tabs worked in pure swing version of JMARS.
Is this something that can be corrected now?
If not, we would need to revert to the pre-centered version of the tabbed pane. Let us know, please.
[TABS-Issue.pdf](https://github.com/vincenzopalazzo/material-ui-swing/files/3209369/TABS-Issue.pdf)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I'm sorry if my commit not works correctly but the component JTabbledPane is not thought of sun developer for a different position to left or right, I have created an adapter for the code OpenJDK for apport the fix in the layout.

For a moment I do not have some time for good work, so In the weekend I going to disable the adapter and the look restore the original layout.

Sorry for this problem.

I have a question for you, can you open an issue with the screenshot the tabbed pane component material so I add the new label if any person want to collaborate with us that adding a new support component. Thanks

**Comment by zanderson9** [comment]
Vincent, I posted this request in a [New Issue](https://github.com/vincenzopalazzo/material-ui-swing/issues/50), as per your preference.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3 thanks so much
