### ISSUE TITLE
scrollbar too light

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#31]
The scrollbar shows up very light by default (almost the same color as the scroll background).  Could it be made darker?
![Screenshot-13](https://user-images.githubusercontent.com/21114460/56063196-77672e00-5d23-11e9-9324-158d415600b0.png)

Also, I know the UI has been updated a bit, but do you think the up and down arrows could be removed completely?  I feel like a more modern feel just has sort of a hovering scroll bar with no arrows?
![Screenshot-14](https://user-images.githubusercontent.com/21114460/56063338-d036c680-5d23-11e9-9ecd-f24de3ba9d74.png)

The second suggestion is not a bug, just an enhancement maybe?

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

Yes
> Also, I know the UI has been updated a bit, but do you think the up and down arrows could be removed completely? I feel like a more modern feel just has sort of a hovering scroll bar with no arrows? 

Yes is more good :)

> Also, I know the UI has been updated a bit, but do you think the up and down arrows could be removed completely? I feel like a more modern feel just has sort of a hovering scroll bar with no arrows?

I have some time tonight and I think I can give you a version with these fixes, maybe I'll add a way to disable the buttons and not remove them completely in the jscroolbar

**Comment by vincenzopalazzo** [comment]
@srcarter3,

For you is good?
![](https://media.giphy.com/media/lKnTcKDbYVK5Sk6PgQ/giphy.gif)

**Comment by srcarter3** [comment]
Yes, that's great!

**Comment by vincenzopalazzo** [comment]
You can now disable the arrows with the following Boolean constant
*ScrollBar.enableArrow*
