### ISSUE TITLE
Checkboxes and RadioButton icon colors

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#32]
I was wondering if there's a way to add a "light" option (white) for the radio buttons and checkboxes.  The foreground only sets the color for the text, but not the icons.  Is it possible to have the foreground also set the color for the icons? Or maybe have another property that can be called to set it to a light option?
Our main new color theme is going to be dark, and it would be helpful to change these icons.  I've attached screenshots of how they look currently.
![Screenshot-18](https://user-images.githubusercontent.com/21114460/56067637-bcde2800-5d30-11e9-9fd2-6343441c302a.png)
![Screenshot-17](https://user-images.githubusercontent.com/21114460/56067638-bcde2800-5d30-11e9-9938-c535393647e2.png)

**Comment by vincenzopalazzo** [comment]
Oh yes :)

**Comment by zanderson9** [comment]
Just to add to Shay's @srcarter3 point, I'm attaching screens from our design, so that is how icons with white outline should look on our dark scheme, with "golden" color being when icon is selected:
![Icons](https://user-images.githubusercontent.com/49419742/56068985-c5852d00-5d35-11e9-9a1a-ebe352fab102.png)
![Icons2](https://user-images.githubusercontent.com/49419742/56068986-c61dc380-5d35-11e9-971a-dc319b404317.png)

**Comment by vincenzopalazzo** [comment]
Add the radio button and checkbox, make me look like the images I chose,

You can try images through the factory
  with the following code

`checkBox.setIcon (new ImageIcon(MaterialImageFactory.getIstance().getImage(MaterialImageFactory.UNCHECKED_WHITE_BOX)));`

and instead the constants with the following name
**RADIO_BUTTON_WHITE_ON**
**RADIO_BUTTON_WHITE_OFF**
**UNCHECKED_WHITE_BOX**
**CHECKED_WHITE_BOX**

I added quickly if there is any problem we will solve it

**Comment by vincenzopalazzo** [comment]
@srcarter3 @zanderson9 
I hope I have been helpful, my day here is over unfortunately, I think there is a good deal of time zone.
Good day and good work

**Comment by zanderson9** [comment]
yes, Vincent @vincenzopalazzo, great work! Thank you

P.S. It is almost 1 am for you now, isn't it?

**Comment by vincenzopalazzo** [comment]
Yes hahhaha

**Comment by vincenzopalazzo** [comment]
Closed for issue resolution.

Into next update, I will add a white icon for all component

**Comment by srcarter3** [comment]
@vincenzopalazzo I wasn't able to get those icons from the most recent jar. Were all the resources and constants added to it?

**Comment by vincenzopalazzo** [comment]
@srcarter3 Yes, but I think maven did everything as it should, so I'll update everything as soon as possible

**Comment by vincenzopalazzo** [comment]
When you commit this evening, you can add white icons with the following code to create an ImageIcon.

`MaterialImageFactory.getIstance().getImage(MaterialImageFactory.UNCHECKED_WHITE_BOX)));`

**Comment by srcarter3** [comment]
Okay great thank you.
If you're making changes to the code, you should update the method to be 
`MaterialImageFactory.getInstance()`

**Comment by vincenzopalazzo** [comment]
@srcarter3 why? the method is not good?

**Comment by srcarter3** [comment]
The correct name of the method you are trying to implement is get**In**stance().  Not getIstance().
Istance is not a word in English, Instance is.

**Comment by vincenzopalazzo** [comment]
@srcarter3 Oh, sorry  :/

**Comment by zanderson9** [comment]
Good Day, Vincent, 
the _**jar**_ in the lib directory is from 3 days ago (prior to the weekend). That _**jar**_ doesn't have image UNCHECKED_WHITE_BOX, I am looking through the decompiler into the MaterialImages.class code.  Not do I find the corresponding image in the resources/imgs folder...

**Comment by vincenzopalazzo** [comment]
Hello @zanderson9 ,
MaterialImage does not exist in my version, but MaterialImageFactory exists, where I don't load images on bootstrap but load them on demand, I don't know why that class still exists, I intend to change my construction system to gradle, but I don't like it though I chose to adopt it

**Comment by vincenzopalazzo** [comment]
@srcarter3 
Fixed, thanks so much

> The correct name of the method you are trying to implement is getInstance(). Not getIstance().
Istance is not a word in English, Instance is.

@zanderson9 fixed, thanks so much

> Good Day, Vincent,
the jar in the lib directory is from 3 days ago (prior to the weekend). That jar doesn't have image UNCHECKED_WHITE_BOX, I am looking through the decompiler into the MaterialImages.class code. Not do I find the corresponding image in the resources/imgs folder...
