### ISSUE TITLE
Highlight color in menus/dropdowns

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#33]
Can the default highlight color be darker for comboboxes and menus?
The hover color is very similar to the regular background, and makes it hard to notice the highlighted item.
![Screenshot-19](https://user-images.githubusercontent.com/21114460/56068934-92db3480-5d35-11e9-89bb-7b812a0546b4.png)
![Screenshot-JMARS 0E 0N](https://user-images.githubusercontent.com/21114460/56068935-92db3480-5d35-11e9-944e-15c4a89681e3.png)

**Comment by vincenzopalazzo** [comment]
You can change it in the UIManager with the following constant, no change it for backwards compatibility with those who already use the look and feel

*"MenuItem.selectionBackground"*

**Comment by srcarter3** [comment]
Okay.  Do you know the property to change the combobox?  
ComboBox.selectionBackground was not right.

**Comment by vincenzopalazzo** [comment]
For the combo box constants are
```
table.put("ComboBox.selectionBackground", Color.WHITE);
table.put("ComboBox.selectionForeground", Color.BLACK);
```

You can find all the constants used in the look and feel here
https://github.com/vincenzopalazzo/material-ui-swing/blob/masternow/src/mdlaf/MaterialLookAndFeel.java

**Comment by srcarter3** [comment]
Ahhh! Thank you for the list of your properties.
The one I needed to change was 
      
`table.put("ComboBox.selectedInDropDownBackground", MaterialColors.GRAY_200);`

**Comment by vincenzopalazzo** [comment]
I will try in the future to change this style of property declaration is a bit ugly

**Comment by vincenzopalazzo** [comment]
Closed for issue resolution
