### ISSUE TITLE
Button changing shape when pressed

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#34]
JButton seems to change shape from "rounded" corners to "square" corners during a mouse pressed event.

I've attached a photo of in focus (my mouse is over the button):
![beforeClick](https://user-images.githubusercontent.com/21114460/56386103-d02c4000-61d5-11e9-88cb-f50c68773792.png)

And then during a mousepressed:
![afterClick](https://user-images.githubusercontent.com/21114460/56386115-d91d1180-61d5-11e9-988d-1ae83a36bf02.png)

I think the button shape should stay the same during a mouse clicked.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3, 
I fixed now this problem, if I create a jar test for you, you will do a testing new look for JDialog and JOption pane? 

This is a new effect
![Selection_002](https://user-images.githubusercontent.com/17150045/56388819-48235600-6228-11e9-9db2-e01c89013952.png)

**Comment by zanderson9** [comment]
@vincenzopalazzo, yes, certainly, we will test as soon as you have new _jar_ for us. Thank you.

**Comment by vincenzopalazzo** [comment]
HI @zanderson9,

The commit is arriving. the effect in JDialog and JOprion pane is enabled whit this code

 ```
static {
        try {
            JDialog.setDefaultLookAndFeelDecorated(true);
            UIManager.setLookAndFeel(new MaterialLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
    }
```
In the cases where I tested it I found no problems but my cases were simple.

The effect was very complete because in that part of the components are contained all the listeners of the movements of the window

**Comment by vincenzopalazzo** [comment]
Close this problem, because was fixed

**Comment by srcarter3** [comment]
@vincenzopalazzo  I will take a look when we put the new jar in our code.  But specifically I was not referring just to OptionPane and JDialogs.  I was referring to all JButtons.

**Comment by vincenzopalazzo** [comment]
yes, the problem of buttons I hope to deal with by Monday, the look of the Joption bread is modern but it's hard to get I hope it works because I really like it a lot.

**Comment by srcarter3** [comment]
I'm not sure what change you mean -- JOption bread? 
And is this possibly commented on the wrong issue. This issue was supposed to be about buttons changing shape when clicked?

**Comment by zanderson9** [comment]
@vincenzopalazzo, Shay and I will take a look at the newly posted _jar_. We will comment shortly about the changes.

**Comment by vincenzopalazzo** [comment]
@srcarter3, @zanderson9

Sorry for my imprecision, Usually I am inclined to create a new release with screen and all indications but lately I am having little time.
I apologize again for my inaccuracy.

I created a new label and set your last issue as a collector where I will notify you of all changes due to the new commits

This is last my update
https://github.com/vincenzopalazzo/material-ui-swing/issues/36

**Comment by lilili87222** [comment]
It may be  better if File Name input textfield have border

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222, 

Yes that's what you're saying and it's a really cool effect, I'll try to work on it in the coming months now I want to go to version 1.0 with a stable look and feel and then redesign a new update

**Comment by vincenzopalazzo** [comment]
HI @lilili87222,
I will try to add this effect, thanks

**Comment by vincenzopalazzo** [comment]
Hi @lilili87222,

Importing the border into the text field forces me to review the whole implementation, this will be done in a new update, I'm happy if you open an issue so I can add it to the things to do inside my project scheduler.

For the moment, I hope that for version 1.0 beta you like
