### ISSUE TITLE
Progress of the project, waiting version 1.0 of the project

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#36]
With cross-commenting on [Issue 34](https://github.com/vincenzopalazzo/material-ui-swing/issues/34#issuecomment-484695869), which inadvertently occurred, it is now confusing what changes **exactly** went into the April 18 **jar**?

@vincenzopalazzo, **_please provide an itemized list of changes_** that went into 
_material-ui-swing-0.9.9.jar_ on April 18 2019.

Having this list of changes will allow us to accurately validate the **jar** for those changes.

- [x] Itemized list of changes for April 18 update
- [x] reference the 'Resolved' Issues which made it into April 18 update

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Sorry, the fixes that have been made are:

                                      REPORT UPDATE 18/04/2019

**Bug fixed**
- [NullPointer into JTextField](https://github.com/vincenzopalazzo/material-ui-swing/issues/24)
- [Icon white](https://github.com/vincenzopalazzo/material-ui-swing/issues/32)
- [Keyborad actions list](https://github.com/vincenzopalazzo/material-ui-swing/issues/29)
- [Removed arrrow to Jscrollbar](https://github.com/vincenzopalazzo/material-ui-swing/issues/31)
- [Border button JButton](https://github.com/vincenzopalazzo/material-ui-swing/issues/34)
- [Default action JOptionPane](https://github.com/vincenzopalazzo/material-ui-swing/issues/20)

**Partial new function**

- Look JTabbledPane
- look JDialog and JOptionPane, the component are not the border of a window when using this code before setting Look and feel `JDialog.setDefaultLookAndFeelDecorated(true);`

**Comment by vincenzopalazzo** [comment]
REPORT UPDATE 19/04/2019

**Bug fixed**
- **Fix paint component JtextFielad and JpasswordFielad**


- More refactoring into code

**Comment by vincenzopalazzo** [comment]
REPORT UPDATE 21/04/2019 for version 1.0 Beta

This version introduces all changes made in the version [0.9.9](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V9.9), And adds the following fixes

**Bug Fixed **
- Fixed issue #35
- Fixed issue #23
- update demo swing
- Fixed issue atarw#81
- Fixed issue atarw#80
- Fixed issue atarw#77
- [NullPointer into JTextField](https://github.com/vincenzopalazzo/material-ui-swing/issues/24)
- [Icon white](https://github.com/vincenzopalazzo/material-ui-swing/issues/32)
- [Keyborad actions list](https://github.com/vincenzopalazzo/material-ui-swing/issues/29)
- [Removed arrrow to Jscrollbar](https://github.com/vincenzopalazzo/material-ui-swing/issues/31)
- [Border button JButton](https://github.com/vincenzopalazzo/material-ui-swing/issues/34)
- [Default action JOptionPane](https://github.com/vincenzopalazzo/material-ui-swing/issues/20)
- Fixed button focusable look
- Added support JList
- Remove Old dependency(*remove MaterialImages, MaterialFonts*)
- Graphic alignment JTextField and JPasswordField

**New Function alpha test**

- **Look JTabbledPane**
![Selection_009](https://user-images.githubusercontent.com/17150045/56470837-408fc700-644b-11e9-8bc7-9b879ea840dd.png)

- **look JDialog and JOptionPane**, the component are not the border of a window when using this code before setting Look and feel 
`JDialog.setDefaultLookAndFeelDecorated(true);`
![Selection_006](https://user-images.githubusercontent.com/17150045/56470798-ccedba00-644a-11e9-959b-47980446b14e.png)
![Selection_007](https://user-images.githubusercontent.com/17150045/56470808-f3135a00-644a-11e9-8848-983c936819da.png)
![Selection_008](https://user-images.githubusercontent.com/17150045/56470815-0aeade00-644b-11e9-9b2c-c820ea410d9b.png)

**Look new Component supported**

**JList**
![Selection_010](https://user-images.githubusercontent.com/17150045/56470877-d1ff3900-644b-11e9-92aa-34e6aa46cb71.png)

**Button default into JOprionPane**
![Selection_011](https://user-images.githubusercontent.com/17150045/56470884-fb1fc980-644b-11e9-92d6-63989ccbb857.png)

**Old look JOptionPane**
![Selection_012](https://user-images.githubusercontent.com/17150045/56470930-74b7b780-644c-11e9-86ae-fba4302caf63.png)
![Selection_013](https://user-images.githubusercontent.com/17150045/56470931-74b7b780-644c-11e9-99a3-5cd9f4e7398b.png)

**New Color**
*Screenshot*
![Selection_014](https://user-images.githubusercontent.com/17150045/56470937-99ac2a80-644c-11e9-93ff-1f1e80901c93.png)

*Constant name*
```
Color DARKLY_STRONG_BLUE
Color DARKLY_BLUE 
Color COSMO_STRONG_BLUE
Color COSMO_BLUE
Color COSMO_LIGTH_BLUE
Color DARKLY_RED 
Color COSMO_RED
Color COSMO_LIGHT_RED
Color COSMO_PURPLE
Color COSMO_LIGHT_PURPLE
Color DARKLY_ORANGE
Color COSMO_ORANGE
Color COSMO_LIGHT_ORANGE
Color DARKLY_STRONG_GREEN
Color DARKLY_GREEN 
Color COSMO_GREEN 
Color COSMO_LIGHT_GREEN
Color COSMO_LIGTH_GRAY
Color COSMO_MEDIUM_GRAY
Color COSMO_STRONG_GRAY
Color COSMO_DARK_GRAY
Color DARKLY_GRAY
Color COSMO_BLACK
```

**Screen demo *swing_set* whit material-ui-swing**
![Selection_015](https://user-images.githubusercontent.com/17150045/56471212-37552900-6450-11e9-83f6-b787974719df.png)
![Selection_016](https://user-images.githubusercontent.com/17150045/56471213-37552900-6450-11e9-86e6-dfa70a931c5b.png)
![Selection_017](https://user-images.githubusercontent.com/17150045/56471214-37552900-6450-11e9-892f-eef1dbd0e893.png)
![Selection_018](https://user-images.githubusercontent.com/17150045/56471215-37edbf80-6450-11e9-85cb-abfb12fbab53.png)
![Gif combo box](https://media.giphy.com/media/1msBgUIqAEOmVoIbGw/giphy.gif)

**Comment by zanderson9** [comment]
Hi Vincent,
I just downloaded the latest library jar, from the libs folder at this location:
https://github.com/vincenzopalazzo/material-ui-swing/tree/V1.0.Beta/libs
The name of the library file is, as before, **material-ui-swing-1.0_Beta.jar** and it is updated "3 days ago", so I take it as the latest update.
This is where you are staging the updated jar for us.

But when I downloaded and unzipped the complete archive, with source code, demos and libs,  from the main page at https://github.com/vincenzopalazzo/material-ui-swing/tree/V1.0.Beta, then I found that the libs folder has library file named **material-ui-swing-1._2_.0_Beta.jar** (note, "2" in the version number).

So are the staged **material-ui-swing-1.0_Beta.jar** and archived **material-ui-swing-1._2_.0_Beta.jar** same libraries?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

All version are aligned at the last commit but [this](https://github.com/vincenzopalazzo/material-ui-swing/tree/V1.0.Beta/libs) is more sicure because I don't know how github manager the different jar with the same name in the release section.

**Comment by vincenzopalazzo** [comment]
REPORT UPDATE 26/05/2019 for version 1.0 Beta

This version introduces all changes made in the version [1.0.Beta](https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/V1.0.Beta), And adds the following fixes

Version 1.0 is coming

- Reverse BasicTablePaneAdapter supported, this solution has more bug
- Added support to JLabel disabled
- Added skill for change icon for checkbox into JTable
- Try to fix the issue for changing cursor into JFrame
- Added support tu RadioButton icon white

This the screenshots
![Selection_014](https://user-images.githubusercontent.com/17150045/58379250-95ba7d80-7fa1-11e9-8927-31a709472b16.png)
![Selection_013](https://user-images.githubusercontent.com/17150045/58379254-994e0480-7fa1-11e9-91b9-352a1e2f0426.png)

A question for you, @zanderson9 @srcarter3  @lilili87222
Next weekend the milestone will expire and I think look-and-feel has become stable even in customizations, I would like to ask you if it is possible to release an official version 1.0

** Version 1.0 is ready for you?**
/polls 'Yes' "No"

**Comment by vincenzopalazzo** [comment]
**Update 9/06/2019**

- Fixed issue https://github.com/vincenzopalazzo/material-ui-swing/issues/58
- Fixed issue https://github.com/vincenzopalazzo/material-ui-swing/issues/57
- Fixed issue https://github.com/vincenzopalazzo/material-ui-swing/issues/56
- Fixed issue https://github.com/vincenzopalazzo/material-ui-swing/issues/55
