### ISSUE TITLE
JButton - improve visual indicator when Disabled

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#37]
When a button is disabled, the current implementation of this library makes a visual indicator of the disabled state by changing the text color. The background color remains the same. See the attached images obtained from the demo for both disabled and enabled state where the difference is only in the text color.
![ButtonEnabled](https://user-images.githubusercontent.com/49419742/56444806-23be8c80-62af-11e9-96f2-6cd028d404df.png)
![DisabledButtonMaterial](https://user-images.githubusercontent.com/49419742/56444807-23be8c80-62af-11e9-8eea-0c9aabc54292.png)

However, according to [Material Design guidelines on Disabled state](https://material.io/design/interaction/states.html#disabled), the background change is highly desirable and offers a much better visual indicator to the user. Also in Swing a disabled button has a different than enabled background.

Can "material" implementation to a disabled button state be provided with this library?

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Absolutely yes, thanks for this fix.

**Comment by zanderson9** [comment]
Additionally, I noticed that when a button was pressed and was in focus, then when it becomes **disabled**, the _focus_ on it remains in a **disabled** state. Please see attached image: "Dock Me" button was pressed, the panel got docked, and "Dock Me" is now disabled, as well as "Close". But _focus_ on "Dock Me" remained. So even though two buttons, "Close" and "Dock Me", are **disabled**, they have different background look due to _focus_ staying on "Dock Me".
![DisabledFocus](https://user-images.githubusercontent.com/49419742/56446117-a0ed0000-62b5-11e9-97a0-669997140712.png)

**Comment by vincenzopalazzo** [comment]
@zanderson9, The focus you are referring to is the 'mouse hover effect?

This effect on the disabled buttons will be resolved thanks to the MaterialManagerListener component, but it is something I will do internally.
I have already given a draft of the component that I will release within the weekend

**Comment by zanderson9** [comment]
As you do changes over the weekend, please keep the Project Progress updated, as well. Thank you!

**Comment by vincenzopalazzo** [comment]
sure, date and changes always updated at each commit, I will update the reference issue, thanks to you for pointing out to me that it was becoming a chaos, today I started putting things in order

**Comment by vincenzopalazzo** [comment]
The addition of this effect was rather difficult, and it is still difficult because there are no ways to declare observable properties in java, for the moment I added the `table.put("Button.disabledText", MaterialColors.GRAY_600);` constant to change the color of the text when the button.

For the effect, I will work on it, sorry if I failed to import it

**Comment by vincenzopalazzo** [comment]
Released version beta 1.3, it added this style
