### ISSUE TITLE
Button : when clicked(depressed) background color is not what expected

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#38]

**Comment by zanderson9** [comment]
With the newest jar (April 23), when I click a button, its background color changes to "grey". However, this change in a background color is not the behavior we specify or expect.
In the attached image, I clicked "Yes".

![Button-background](https://user-images.githubusercontent.com/49419742/56622268-33f2a680-65e4-11e9-9d97-5594d096fbf1.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, I hope that this problem is was resolved whit the new commit.

I attend your feedback.

Sorry for this problem but in the version 1.0 beta is changed a lot of components

**Comment by zanderson9** [comment]
@vincenzopalazzo, I am not finding the latest library _jar_ in the _libs_ directory. As of now (April 24) the _libs_ directory contains only _material-ui-swing-0.9.9.jar_ dated April 21 2019.
With 1.0 beta in place, I would expect to find _material-ui-swing-1.0.beta.jar_, but I'm not seeing it. Please advise.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This problem was fixed with last update?

**Comment by zanderson9** [comment]
Yes, is resolved.
