### ISSUE TITLE
Light icons wanted

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#39]
Wondering if we can have "light-color" icons for the FileChooser dialog?
The background color throughout JMARS is dark grey, #2D3038, or  RGB(45, 48, 56).
As such, black icons are not visible, see List and Details on the attached image.
Can we have a version with white icons or an ability to override the black icons with our light-color version?
![Darkicons](https://user-images.githubusercontent.com/49419742/56772029-7e535f00-676d-11e9-8323-3f105ce545a0.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I wiil add this functions into next days, Thanks you :)

**Comment by vincenzopalazzo** [comment]
HI @zanderson9,

I have fixed this problem.

Add constant for the icon JFileChooser, the constant is
  ```
  "FileChooser[icons].computer"
    "FileChooser[icons].directory"
    "FileChooser[icons].file"
    "FileChooser[icons].floppyDrive"
    "FileChooser[icons].hardDrive"
    "FileChooser[icons].home"
    "FileChooser[icons].list"
    "FileChooser[icons].details"
    "FileChooser[icons].newFolder"
    "FileChooser[icons].upFolder"
```
and the icons are two color BLACK and WHITE such as the RINGO :)
    ```
MaterialImageFactory.COMPUTER_COLOR
    MaterialImageFactory.FOLDER_COLOR
    MaterialImageFactory.FILE_COLOR
    MaterialImageFactory.FLOPPY_DRIVE_COLOR
    MaterialImageFactory.HARD_DRIVE_COLOR
    MaterialImageFactory.HOME_COLOR
    MaterialImageFactory.LIST_COLOR
    MaterialImageFactory.DETAILS_COLOR
    MaterialImageFactory.NEW_FOLDER_COLOR
    MaterialImageFactory.BACK_ARROW_COLOR 
```

**Comment by zanderson9** [comment]
Hi @vincenzopalazzo ,
white icons worked well, thank you.
But as I chose white icons and can now see them better, I find that there is no space between "Details" and "List" icons?..
![FileChooser](https://user-images.githubusercontent.com/49419742/56934880-d0182400-6aa2-11e9-80b1-5c1a46451f02.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Thanks for your feedback and this is a bug for library and I'm going to fix it.

Now I can ask you to open a new issue for this bug so I'm going to add the bug to the scheduler project, thanks so much

**Comment by zanderson9** [comment]
One more request on this, please: we have a dark UI theme, so the dark toggle buttons are nearly invisible on a dark background (image attached). Can you add light toggle buttons to the library, similarly, as you added other light icons?
![Toggles](https://user-images.githubusercontent.com/49419742/58140198-0dc82280-7bf3-11e9-8760-5385b0e21e5b.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Yes, I going to add support in the weekend.
