### ISSUE TITLE
Arrows are reversed in TaskPane

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#40]
It appears, that arrows are "reversed" in JXTaskPane. Please See attached

Also, please verify spelling inside the library _MaterialLookAndFeel.java_, lines 437 and 438 for TaskPane image settings. It is spelled "Collassed", but should be "Collapsed".

![Arrows](https://user-images.githubusercontent.com/49419742/56773714-3b48ba00-6774-11e9-88bd-10cde4c9672e.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Sorry me for this problem, yes this problem will resolve into next days.

Thanks for your help 

JMars now is very cool :) congratulations

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I added new name in the last commit, but I not change the direction arrow but the arrow have changed in for resolve this issue https://github.com/atarw/material-ui-swing/issues/66

In order not to create instability with previous versions I decided to keep it that way because otherwise I would have to wait for another issue from someone who would like the inverted arrows.

Excuse me, however you can quickly resolve with the following code

```
table.put("TaskPane.yesCollasped", new ImageIcon(MaterialImageFactory.getInstance().getImage(MaterialImageFactory.NO_COLLAPSED)));
table.put("TaskPane.noCollaspsed", new ImageIcon(MaterialImageFactory.getInstance().getImage(MaterialImageFactory.YES_COLLAPSED)));

```
```
Hope you got help

**Comment by zanderson9** [comment]
Hi @vincenzopalazzo,

I am able to apply the change directly in my code, so that arrow pointing right is "collapsed" state and arrow pointing "down" is expanded state. 
This solves the problem.
But the downside of such an approach is that we introduce tight coupling between custom code and the library. So in the future, we may want to rethink this and see how to better decouple the library and the code that uses it.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

If I will add a new variable boolean TaskPane[icon].reverse for reverse the icon task pane default, this will resolve your problem of the coupling? 

In next version but not into the 1.0, I want to add the configuration with the file proprieties, an example:
if into classpath exist materilPersona.proprieties setting this configuration than setting materilDefaul.propietis configuration

**Comment by zanderson9** [comment]
Hi Vincent,
we can leave the code as is for now and not introduce a boolean variable.
Your suggestion about having configurable properties is better, so let's think this through and consider implementing it post 1.0 to improve coupling issues.
Thank you.

**Comment by vincenzopalazzo** [comment]
Hi  @zanderson9, 
OK, thanks to you for help
