### ISSUE TITLE
No space between icons "Details" and "List" in FileChooser dialog

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#41]
In FileChooser dialog, there is no space between "Details" and "List" icons ("White"-color version), upper right corner.
![FileChooser](https://user-images.githubusercontent.com/49419742/56987056-44a1a000-6b41-11e9-9623-912ae09cde47.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I added this change 

This is the [reference](https://github.com/vincenzopalazzo/material-ui-swing/issues/36) for the changes
I attend your feedback, thanks so much
