### ISSUE TITLE
Setting to Make Dialog Title bold

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#44]
Non-bold title in a dialog doesn't stand out... Can it be set to bold, if optionally?

![Title](https://user-images.githubusercontent.com/49419742/57002121-e3de8b80-6b71-11e9-827c-cab5b25c3b45.png)

**Comment by vincenzopalazzo** [comment]
HI @zanderson9,

Yes the font is configurable whit this constant: "InternalFrame.titleFont".

Try this constant and you say me feedback, thanks you :)

**Comment by zanderson9** [comment]
Worked. Great!
