### ISSUE TITLE
Dont change UI Text button of OptionDialog

### ISSUE THREAD

**Issue by NhocKun** [vincenzopalazzo/material-ui-swing#46]
I cant set custom text [OK] [Cancel] of OptionDialog for localtize, pls help
Ex:
`UIManager.put("OptionPane.cancelButtonText", cancelText);
UIManager.put("OptionPane.okButtonText", okText);`

**Comment by vincenzopalazzo** [comment]
Hi @NhocKun,

The button of JOptionPane does not depend for the Material-ui-swing, [this is a referiment](https://stackoverflow.com/questions/13334198/java-custom-buttons-in-showinputdialog) for customizing a button for JOprionPane.

Give me feedback for this your problem

**Comment by NhocKun** [comment]
> Hi @NhocKun,
> 
> The button of JOptionPane does not depend for the Material-ui-swing, [this is a referiment](https://stackoverflow.com/questions/13334198/java-custom-buttons-in-showinputdialog) for customizing a button for JOprionPane.
> 
> Give me feedback for this your problem

Hi @vincenzopalazzo  thanks for you respone, i have change button text using custom param like you suggestion. I close question. Thanks again :+1:
