### ISSUE TITLE
Dialog border

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#47]
I wrote you a personal email about this, but figured it would be worth noting on her as well.

I noticed that the jdialogs (option panes) don't seem to have any kind of buffer or spacing on the interior.  All components added are positioned right up to the edges of the dialog (see attachments).
I tried adding
`UIManager.put("OptionPane.border", BorderFactory.createEmptyBorder(5, 5, 5, 5));`
but that did not make a difference.
![Screenshot-Confirm Exit](https://user-images.githubusercontent.com/21114460/58132729-ef542e00-7bd6-11e9-9914-f2c738792fe2.png)
![Screenshot-JMARS-2](https://user-images.githubusercontent.com/21114460/58132731-ef542e00-7bd6-11e9-8d0b-f0f9156b5ab0.png)

**Comment by srcarter3** [comment]
Setting the border does change the dialog.  I was running the wrong project. My apologies.

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

Your resolve your problem with this constant
```
table.put("RootPane.frameBorder", BorderFactory.createEmptyBorder());
table.put("RootPane.background", MaterialColors.WHITE);
```

Give me feedback when you have the results, good work
