### ISSUE TITLE
Scrollable Tabs - is it possible?

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#48]
Hi @vincenzopalazzo,

we are running into a problem with tabs, when there are too many tabs to display and not enough window width. In such case, the tabs are displayed in multiple rows, and the behavior of the **ordering** of the tabs is **changing** when any tab is clicked. 

Attached document shows the scenarios we ran into.

According to the[ Material Design Tabs guidelines](https://material.io/design/components/tabs.html#scrollable-tabs), tabs, when not fitting in a window, should be implemented as scrollable. There is even a specific mention in the Design for the Desktop, where it is recommended to have a visual indicator "**>**" to let the user know there are more tabs, as seen in this image:

![Tabs-scroll](https://user-images.githubusercontent.com/49419742/58212957-648e3480-7ca5-11e9-9e49-ee5233cf3f30.png)

So what, in your opinion, are our options to solve this problem, when tabs do not fit and get messed up when clicked?
[TABS-WrongOrder.pdf](https://github.com/vincenzopalazzo/material-ui-swing/files/3209549/TABS-WrongOrder.pdf)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I say into this post and I have a question for you.
 
https://github.com/vincenzopalazzo/material-ui-swing/issues/30

I am closing this issue for the official issue from you with all the changes will be done to JTabbedPane component
