### ISSUE TITLE
Checkbox items in JTable - visibility

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#49]
Hi @vincenzopalazzo,
I'm wondering if there is a property we can set on **JTable** to control a **checkbox** table item?
We have tables with a light background, and, as seen in the image, the light checkboxes are hardly visible. Can the library offer help with this?

![TableCheckboxes](https://user-images.githubusercontent.com/49419742/58218166-cad18200-7cba-11e9-8c22-2e166c579328.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

I'm afraid of no but I look this problem into the weekend

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Now is possible to change the icon with this constant
```
table.put("Table[CheckBox].checked", yourIcon);
table.put("Table[CheckBox].unchecked", yourIcon);
```

**Comment by zanderson9** [comment]
Hi @vincenzopalazzo,
thank you for the proposed solution.
Unfortunately, it didn't have the desired effect in our code. Maybe because we have a custom table that extends JTable.
But what did work is writing code to set the desired icons ("black"-outline checkboxes from the MaterialImage factory) in that custom table's renderer and editor.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

Sorry if my solution not work but the icon in the table has the life cycle more complex.

If you extend the jTable you should try this code in your class, I resolved with this code
https://github.com/vincenzopalazzo/material-ui-swing/blob/c4c0efeb77cc8d29666188f62dce9567e71c238c/src/mdlaf/components/table/MaterialTableUI.java#L60-L70
