### ISSUE TITLE
Label.disableForeground does not work

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#51]
I am trying to change the color of JLabels when they are disabled.  I believe the following line **should** work, but it does not: 
`UIManager.put("Label.disabledForeground", myColor);`

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

This skill is not implemented, I going to implement it in this weekend, thanks

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

Now is possible to configure the color  JLabel with this constant

```
table.put("Label[disabled].font", MaterialFontFactory.getInstance().getFont(MaterialFontFactory.ITALIC));
table.put("Label[disabled].background", MaterialColors.WHITE);
table.put("Label[disabled].foreground", MaterialColors.COSMO_BLACK);
```

the default style is
![Selection_014](https://user-images.githubusercontent.com/17150045/58379221-42e0c600-7fa1-11e9-9b9b-73c6127a2f25.png)

**Comment by zanderson9** [comment]
Hi @vincenzopalazzo,

unfortunately, this solution didn't work for us: disabled labels remain "invisible" (attached document).

I wonder if swing's UIManger "understands" the key with a modifier in square "[] "brackets?

[InvisibleText.pdf](https://github.com/vincenzopalazzo/material-ui-swing/files/3221677/InvisibleText.pdf)

**Comment by vincenzopalazzo** [comment]
HI @zanderson9,

Thanks for your feedback, I have worked on this problem this morning and this problem going to resolve in the next commit

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9 into this commit I resolved this problem
