### ISSUE TITLE
Task Pane behavior changed in latest release 1.0 [beta]

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#54]
With the latest build (May 26 2019) there is a problem with Task Pane control: the Task Pane collapse/contract repaint is incorrect.

The issue is described in the attached document.

[TaskPane-Issues.pdf](https://github.com/vincenzopalazzo/material-ui-swing/files/3221310/TaskPane-Issues.pdf)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This error is very strange but I have worked today and I resolved this in the next commit

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9,

This bug has was resolved into the last jar?

**Comment by zanderson9** [comment]
Hi Vincent,
The Task Pane looks different in the latest jar than in the jar when I reported the error. But it is still "broken" for us.
We nailed the looks of Task Pane long ago and cannot afford to keep changing it. So we reverted back to pre-May 26 release. With all the library releases prior to May 26 we were able to maintain this look.

here is the look we are using - 

Expanded (pre-May 26 release)
![TaskPane-expand](https://user-images.githubusercontent.com/49419742/58585560-e7ffd680-820d-11e9-834b-f11044ec6842.png)

Collapsed:
![TaskPane-collapse](https://user-images.githubusercontent.com/49419742/58587929-66ab4280-8213-11e9-929e-8b861f436d06.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, Yesterday I resolved this bug, now the JTaskPane is same to the picture

**Comment by zanderson9** [comment]
yes, it is. Thank you.

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, Into this commit, I resolved the problem the JTaskPane, new the fix is official
