### ISSUE TITLE
Disabled text on toggle buttons cannot be set

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#57]
The property for disabled text on toggle buttons cannot be overridden.

ie.

`UIManager.put("ToggleButton.disabledText", theme.getDisabledTextColor());`

and 

`UIManager.put("ToggleButton[disabled].foreground", theme.getDisabledTextColor());`

Do not change the appearance of disabled toggle buttons.  Notice "3D" is set to black, and cannot be overridden (making it very hard to see at all with a dark background).
![Screenshot-JMARS (for Triton) 0E 0N-3](https://user-images.githubusercontent.com/21114460/58915243-6b6d6c00-86d5-11e9-9ea6-9fcfb66bc6a0.png)

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

This bug no longer exists.
