### ISSUE TITLE
SplitPane does not seem to change color

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#58]
I'm trying to change the color of the split pane divider.  None of the below settings seem to do anything:
        `UIManager.put("SplitPaneDivider.background", Color.YELLOW);`
        `UIManager.put("SplitPane.highlight", Color.YELLOW);`
        `UIManager.put("SplitPane.dividerFocusColor", Color.YELLOW);`
        `UIManager.put("SplitPane.darkShadow", Color.YELLOW);`
        `UIManager.put("SplitPane.activeThumb", Color.YELLOW);`

Setting the dragging color **works:**
 `UIManager.put("SplitPaneDivider.draggingColor", Color.YELLOW);`

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3, I look at this problem and the unique constant utils are

```
table.put("SplitPane.border", BorderFactory.createEmptyBorder());
table.put("SplitPane.background", MaterialColors.WHITE);
table.put("SplitPane.dividerSize", 5);
table.put("SplitPaneDivider.border", BorderFactory.createEmptyBorder());
table.put("SplitPaneDivider.background",MaterialColors.WHITE); 
```

For a change, your color at the line use these constants
```
table.put("SplitPane.background", MaterialColors.WHITE);
table.put("SplitPaneDivider.background",MaterialColors.WHITE); 
```
You use both of them because the life cycle is complex and if you use only one constant of the two you could have different effect with different SO

**Comment by srcarter3** [comment]
@vincenzopalazzo 

I tried using the following:

`UIManager.put("SplitPane.background", Color.YELLOW);`
`UIManager.put("SplitPaneDivider.background", Color.YELLOW); `

But that did not change the color of the divider (still light gray).
It did change the color of the underlying background of the split pane, which is not desirable.  See the screenshot.
When the map on the right is loading, you see the background of the split pane (yellow).
![Screenshot-JMARS 0E 0N-18](https://user-images.githubusercontent.com/21114460/59231765-bfc19180-8b96-11e9-8fac-eb00dcc313a2.png)

**Comment by vincenzopalazzo** [comment]
Hi @srcarter3,

With your code, I'm getting this effect and not is wrong 
![Selection_052](https://user-images.githubusercontent.com/17150045/59292109-a135c600-8c7c-11e9-93e1-6ac4f2d536ca.png)

**Comment by srcarter3** [comment]
Let me try with the latest library.

**Comment by srcarter3** [comment]
This is working in the latest library.

Changed the color to a darker gray than the default:
![sliderColor](https://user-images.githubusercontent.com/21114460/59296419-cf92b180-8c3a-11e9-8868-b9bdaac6428f.png)

**Comment by vincenzopalazzo** [comment]
@srcarter3 Good news, I'm closing the problem
