### ISSUE TITLE
Table not respecting overriding class for colors

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#59]
I have a class that extends JTable and overrides the prepareRenderer method:

`public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {`
`	Component c = super.prepareRenderer(renderer, row, column);`
`	KRCDataPoint dp = myModel.getDataPoint(row);`	
`	Color fgColor = getForeground();`
`	if(dp.getDayData() == null || dp.getYearData() == null){`
`		fgColor = missingPlot;`
`	}`
`	c.setForeground(fgColor);`	
`	return c;`
`}`

It's supposed to change the color of the row if the datapoint has no data yet.
It works in the old metal look and feel, but does not with the new material library (see screenshots).

![krcTableOld](https://user-images.githubusercontent.com/21114460/59317577-7184bf00-8c78-11e9-9fba-07090977cbf5.png)
![krcTableNew](https://user-images.githubusercontent.com/21114460/59317584-73e71900-8c78-11e9-9555-824441791bb1.png)

**Comment by vincenzopalazzo** [comment]
This bug is resolver into the last commit :)
