### ISSUE TITLE
Default Button and Button Focus act weird.

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#60]
I have a dialog that's created from a JOptionPane:
`final JOptionPane op =  new JOptionPane(  loginDialogContents,  JOptionPane.PLAIN_MESSAGE,  JOptionPane.OK_CANCEL_OPTION);`

The OK button is the default button:
![Screenshot-JMARS-4](https://user-images.githubusercontent.com/21114460/59390397-faa5ff80-8d25-11e9-999b-f4c3cd0e6b45.png)

But if I tab to change focus, the underline will move from the default button:
![Screenshot-JMARS-1](https://user-images.githubusercontent.com/21114460/59390435-11e4ed00-8d26-11e9-9be8-7cf54396959a.png)

If I click on another button, during the *pressed* the button is both underlined and outlined:
![Screenshot-JMARS](https://user-images.githubusercontent.com/21114460/59390440-14dfdd80-8d26-11e9-9dae-02b2bcaaba2b.png)

**Comment by vincenzopalazzo** [comment]
I Fixed it, is available into the developing branch

**Comment by vincenzopalazzo** [comment]
Released version beta 1.3, it added this style
