### ISSUE TITLE
Table Feature Request

### ISSUE THREAD

**Issue by srcarter3** [vincenzopalazzo/material-ui-swing#61]
This is not a bug, rather a request, if possible.

In our current design we have been alternating row color in tables.  It is done by overriding JTable with this line of code in the prepareRenderer method:

		//for alternating row color
		if (!isRowSelected(row)){
			if(row%2==1) {
				c.setBackground(altRowColor);
			}else{
				c.setBackground(getBackground());
			}
		}

I was wondering if it could be possible to set some kind of boolean and color on the Table in the UIManager.put() method?

The resulting table looks like this:
![Screenshot-MCD Point Layer Options-1](https://user-images.githubusercontent.com/21114460/59467982-d7db2000-8de5-11e9-884c-342227a26a0c.png)

**Comment by vincenzopalazzo** [comment]
@srcarter3  Oh this is very cool idea, I think that I will import into the project in native form, thanks so much

**Comment by vincenzopalazzo** [comment]
Released version beta 1.3, it added this style
