### ISSUE TITLE
Add Border to JButton - Also Allow to Selectively Draw that Border

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#67]
as per our Slack Thread of July 24, 2019, we need to add a border to JButton to allow "material" effect of "Default-Enabled" vs "Enabled-Not-Default"

![Button-Border](https://user-images.githubusercontent.com/49419742/61835069-250fd000-ae2f-11e9-8439-cb79b41c2254.png)

<img width="899" alt="Screen Shot 2019-07-23 at 3 53 51 PM" src="https://user-images.githubusercontent.com/49419742/61835108-56889b80-ae2f-11e9-8184-b007134645b5.png">

**Comment by vincenzopalazzo** [comment]
This function is available now in the developer branch, now is a beta function of the library
