### ISSUE TITLE
TextField Selection Foreground

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#72]
Text Field is not responding properly to **TextField.selectionForeground** setting.

Image 1 - shows the result when **TextField.selectionForeground** is set to BLACK - it changes the **actual** text color **foreground** instead.

Image 1

![blackcolor](https://user-images.githubusercontent.com/49419742/63893620-82072480-c99f-11e9-8734-89efecb56d44.png)

On the other hand, if we keep text foreground color WHITE, then selection foreground remains WHITE when a highlight is placed over it. See Image 2

Image 2

![whitetext](https://user-images.githubusercontent.com/49419742/63893695-b844a400-c99f-11e9-8b76-5fde3e5d0c26.png)

**Comment by vincenzopalazzo** [comment]
The version 1.0.2 resolved this bug, thank so much
