### ISSUE TITLE
Buttons: No response to "Disabled" background and text Color settings

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#79]
With the latest version 1.0.2, I noticed that a disabled button does not respond to the theme settings for color.
I have these entries in UIManager, **as an example**:
UIManager.put("Button.disabledText", Color.RED);
UIManager.put("Button[disabled].background", Color.BLUE);

But regardless of these settings, the button **always** appears in Color.Gray (see attached)

![Buttons-Disabled](https://user-images.githubusercontent.com/49419742/65075056-fdc71200-d94a-11e9-857f-95f8e310b37b.png)

**Comment by vincenzopalazzo** [comment]
Hi @zanderson9, with all version Material library this bug exists because, the MaterialButtonUI Extends the BasicButtonUI, and BasicButtonUI using this code for paint text

```
 protected void paintText(Graphics g, JComponent c, Rectangle textRect, String text) {
        AbstractButton b = (AbstractButton) c;
        ButtonModel model = b.getModel();
        FontMetrics fm = SwingUtilities2.getFontMetrics(c, g);
        int mnemonicIndex = b.getDisplayedMnemonicIndex();

        /* Draw the Text */
        if(model.isEnabled()) {
            /*** paint the text normally */
            g.setColor(b.getForeground());
            SwingUtilities2.drawStringUnderlineCharAt(c, g,text, mnemonicIndex,
                                          textRect.x + getTextShiftOffset(),
                                          textRect.y + fm.getAscent() + getTextShiftOffset());
        }
        else {
            /*** paint the text disabled ***/
            g.setColor(b.getBackground().brighter());
            SwingUtilities2.drawStringUnderlineCharAt(c, g,text, mnemonicIndex,
                                          textRect.x, textRect.y + fm.getAscent());
            g.setColor(b.getBackground().darker());
            SwingUtilities2.drawStringUnderlineCharAt(c, g,text, mnemonicIndex,
                                          textRect.x - 1, textRect.y + fm.getAscent() - 1);
        }
    }
```


I know this problem, I find it with the test regression, but form moment I don't have a good idea to resolve it, I will work on to find the solution

**Comment by zanderson9** [comment]
Thank you for this detailed explanation. I understand now why the problem exists.

**Comment by vincenzopalazzo** [comment]
This issue was fixed, now on the constant UIManager the button response well

The constants are

table.put("Button.disabledBackground", COLOR);
table.put("Button.disabledForeground", COLOR);
