### ISSUE TITLE
Tabbing and TextField - Redraw issue

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#80]
With material lib 1.0.2 we are noticing the following problem:

In a TabPane, if using a text field under one of the Tabs and then changing to another Tab, that "active" text field gets "redrawn" on that other Tab. 

Steps to reproduce in JMARS:

1. Select Crater Counting layer
2. draw few craters on Main view
3. dbl click Crater Counting layer in Left Panel to bring Focus panel
4. Select "Notes" tab and type any text in any text field
5. Switch to any other Tab, for ex., Display or Settings
6. Observe the most-recently-active text field from Notes tab reappears on another Tab's screen

Note: this is observed in various Tab Panes in the application, not just Crater Counting

Attached are screens
![Tab-Text-Step1](https://user-images.githubusercontent.com/49419742/65208932-5e3d7880-da4b-11e9-86c8-8886be94cfa5.png)

![Tab-Text-Step2](https://user-images.githubusercontent.com/49419742/65208933-5e3d7880-da4b-11e9-8a46-46ae1e7f9bfa.png)

**Comment by vincenzopalazzo** [comment]
This bug is fixed in the version 1.0.3, it was a problem with the life cycle Swing
