### ISSUE TITLE
Getting an error while trying to build the demo on 1.0.3

### ISSUE THREAD

**Issue by TheRolfFR** [vincenzopalazzo/material-ui-swing#82]
Hey, I have been trying to load the demo but with a custom theme and I have this error saying that he can't find this :
```
F:\Desktop\TheRolf\Java\Material swing demo\src\org\therolf\ExternalInput\MaterialDarkTheme.java
Error:(69, 35) java: cannot access sun.swing.ImageIconUIResource
  class file for sun.swing.ImageIconUIResource not found
```
It is really annoying because I wanted to finish this theme for you.
I searched the web but didn't found any explanation.

Thanks in advance.

**Comment by vincenzopalazzo** [comment]
Can you give me other information? you have the code hosted on github? can you give me a link

The ImageIconUIResource is a Swing class

**Comment by TheRolfFR** [comment]
I have uploaded it here : https://github.com/TheRolfFR/MaterialDarkTheme

**Comment by vincenzopalazzo** [comment]
@TheRolfFR I have fixed the problem with gradle, I have created a pull request https://github.com/TheRolfFR/MaterialDarkTheme/pull/1

**Comment by vincenzopalazzo** [comment]
Closed it for inachive
