### ISSUE TITLE
No icon on JOptionPane

### ISSUE THREAD

**Issue by Ombrelin** [vincenzopalazzo/material-ui-swing#83]
When calling a JOptionPane, the icon is not displayed

```java
JOptionPane.showMessageDialog(this.view, exception.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
```
![image](https://user-images.githubusercontent.com/47502331/66309302-8d882c80-e909-11e9-9574-5dcaf055bcf2.png)

**Comment by vincenzopalazzo** [comment]
The icons in the JOptionPane are disabled, is possible to enable it with this code

`table.put("OptionPane.enableIcon", true);`

Or if you use the MateriaTheming System, is possible to override this method
```
boolean getEnableIconOptionPane(){
   return true;
}
```

If you use the icon, I advise you to add this code 

`JDialog.setDefaultLookAndFeelDecorated(false);
`
