### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by lovechenghao** [vincenzopalazzo/material-ui-swing#87]
Chinese garbled

**Comment by vincenzopalazzo** [comment]
Hello @lovechenghao  if you give me more information, I can help you

**Comment by kemege** [comment]
I'm using material-ui-swing in a project with OpenJDK 11.0.2 under Windows 10.
It looks like Chinese characters are displayed as squares after using material-ui-swing, but when I use the built-in lookandfeels they all look fine.
Did this lookandfeel use any special font that does not support Unicode characters?

**Comment by vincenzopalazzo** [comment]
Hi @kemege,
In the L&F I'm using the "Noto sans" for support more character, this is [the issue](https://github.com/atarw/material-ui-swing/issues/42)

For reproducing the problem, can you give me an example, please? can you sent it at my email, 

_vincenzopalazzodev@gmail.com_

**Comment by vincenzopalazzo** [comment]
@kemege my simple test have this result 
![Selection_024](https://user-images.githubusercontent.com/17150045/68069359-9b419e00-fd5f-11e9-900e-0900fbebcc8d.png)

**Comment by kemege** [comment]
Hi @vincenzopalazzo,
I just sent you an email with an example project.
Below is the result of my simple test with material-ui-swing and the default Metal LookAndFeel, it's strange that Chinese characters display correctly in some places, but most of them are still squares.
![图片](https://user-images.githubusercontent.com/4485522/68079970-761b6100-fe2d-11e9-9ed4-7f04a3d3d522.png)
![图片](https://user-images.githubusercontent.com/4485522/68079975-8d5a4e80-fe2d-11e9-8bcf-511d9bd32c8d.png)

**Comment by vincenzopalazzo** [comment]
Thanks so much, @kemege, you help me to found 2 bugs in the L&F.
The bugs are.

1. When I have implemented the MaterialThemingSystem I haven't set the personal font into jtextFiled.

2. The selected text color in the JtextArea does not work correctly.

Bug 1 introducing the strange effect, but the Noto Sans does not support your language ([look this](https://github.com/googlefonts/noto-cjk/issues/53)), now I have two solutions.

1. Using MaterialTheming for setting a new font

2. Implement the solution inside the L&F but I will need the time for design the change font when it isn't valid for the language.

I suggest you're the solution 1 because it  is the solution cleanest.

This is the code, you can  create your personal MaterialTheme, an example:

package com.kemege.test;

import mdlaf.themes.MaterialLiteTheme;

```
/**
 MaterialOrientalFontsTheme (c) by Vincenzo Palazzo vincenzopalazzodev@gmail.com
 MaterialOrientalFontsTheme  is licensed under a
 Creative Commons Attribution-ShareAlike 4.0 International License.
 You should have received a copy of the license along with this
 work.  If not, see <http://creativecommons.org/licenses/by-sa/4.0/>.
 */
package com.kemege.test;

import mdlaf.themes.MaterialLiteTheme;

import java.awt.*;

/**
 * @author https://github.com/vincenzopalazzo
 */
public class MaterialOrientalFontsTheme extends MaterialLiteTheme {

    @Override
    protected void installFonts() {

        /*this.fontBold = new javax.swing.plaf.FontUIResource("Noto Sans", Font.BOLD,14);
        this.fontItalic = new javax.swing.plaf.FontUIResource("Noto Sans", Font.ITALIC,14);
        this.fontMedium = new javax.swing.plaf.FontUIResource("Noto Sans", Font.PLAIN,14);
        this.fontRegular = new javax.swing.plaf.FontUIResource("Noto Sans", Font.PLAIN,14);*/

        this.fontBold = new javax.swing.plaf.FontUIResource(Font.SANS_SERIF, Font.BOLD,12);
        this.fontItalic = new javax.swing.plaf.FontUIResource(Font.SANS_SERIF, Font.ITALIC,12);
        this.fontMedium = new javax.swing.plaf.FontUIResource(Font.SANS_SERIF, Font.PLAIN,12);
        this.fontRegular = new javax.swing.plaf.FontUIResource(Font.SANS_SERIF, Font.PLAIN,12);
    }
}

```

Inside the your FrameTest

```
try {
            UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialOrientalFontsTheme()));
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
```

The final effect

![Selection_025](https://user-images.githubusercontent.com/17150045/68086319-d7056200-fe4a-11e9-890a-ece6aa04cf80.png)

**Comment by kemege** [comment]
Thanks for your help, @vincenzopalazzo 
Now it works well after setting the font.

**Comment by vincenzopalazzo** [comment]
I'm happy @kemege.

Thank you for using the MaterialTheming System.

**Comment by YiluoE** [comment]
这的确解决了 设置为您的主题时中文乱码的问题！
但是再继续设置主题颜色时又会出现中文乱码....例如下面的代码
UIManager.setLookAndFeel (new MaterialLookAndFeel(new ChineseSupportClass()));
if (UIManager.getLookAndFeel() instanceof MaterialLookAndFeel)
    {
        MaterialLookAndFeel.changeTheme(new JMarsDarkTheme());
    }
主要是 MaterialLookAndFeel.changeTheme(new JMarsDarkTheme());
会再次出现中文乱码

**Comment by vincenzopalazzo** [comment]
HI @YiluoE,

Sorry for the delay in the answer, but I took a pause this weekend.

For your problem, I want to introduce MaterialTheming, if you understand how to work you can resolve your problem.

## MaterialTheming

MaterialTheming is a second layer for configuring proprieties of look and feel, with it you can not configure propriety with UIManager.put("Button.backgroudnd", SOME COLOR); but you can define the color inside the method installColors() of MaterialTheming, like this

https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/themes/JMarsDarkTheme.java#L92-L177

So, for each theme MaterialLiteTheme, MaterialOceanicTheme, JMarsDarkTheme exist a method for install fonts, like this

https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/themes/JMarsDarkTheme.java#L27-L32

If you want to use the JMarsDarkTheme you must create your theme with that extend the JMarsDarkTheme and override the installFonts() method.

So, if you want to use the MaterialLiteTheme, MaterialOceanicTheme and JMarsDarkTheme you must be create 3 personal themes that extend the default material theme and override the method installFonts() for each personal theme.

I hope this answer helped you.

**Comment by YiluoE** [comment]
> 嗨@YiluoE，
> 
> 很抱歉延迟回答，但这个周末我暂停了一下。
> 
> 对于您的问题，如果您了解如何使用它，那么我想介绍MaterialTheming，并且可以解决您的问题。
> 
> ## 材质主题
> MaterialTheming是用于配置外观适当性的第二层，有了它，您将不再使用UIManager.put（“ Button.backgroudnd”，SOME COLOR）配置适当性；但您可以在MaterialTheming的installColors（）方法中定义颜色，如下所示
> 
> https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/themes/JMarsDarkTheme.java#L92-L177
> 
> 因此，对于每个主题MaterialLiteTheme，MaterialOceanicTheme，JMarsDarkTheme，都存在一种安装字体的方法，例如
> 
> https://github.com/vincenzopalazzo/material-ui-swing/blob/74cbc1c54c285190571508781ec1863c83453480/src/main/java/mdlaf/themes/JMarsDarkTheme.java#L27-L32
> 
> 如果要使用JMarsDarkTheme，则必须使用扩展的JMarsDarkTheme创建主题，并覆盖installFonts（）方法。
> 
> 因此，如果要使用MaterialLiteTheme，MaterialOceanicTheme和JMarsDarkTheme，则必须创建3个个人主题，这些主题扩展了默认的材质主题并覆盖了每个个人主题的installFonts（）方法。
> 
> 希望这个答案对您有所帮助。

谢谢您的帮助，我会跟努力的学习如何使用它，因为它实在是太漂亮了

**Comment by vincenzopalazzo** [comment]
HI @YiluoE,

>谢谢您的帮助，我会更努力的学习如何使用它，因为它实在是太漂亮了

Thanks for your kind words and sorry if I don't have time to implement documentation, but I will work for fix this problem
