### ISSUE TITLE
TABS "Underline" Effect

### ISSUE THREAD

**Issue by zanderson9** [vincenzopalazzo/material-ui-swing#92]
Can we possibly add the "underline" effect to the TabPane (see "grey" underline that spans all tabs in the attached image)?  
This effect gives a neat look to the tabs, as if they "sit" along the common line. JMARS UX team had suggested this visual improvement.

I can currently achieve this effect by writing code where TabPane is used.
But it may be that I need to change code in "many" places to address all TabPanes that JMARS has.
So if we can have this "underline" setting via library, that will be great.

![Tabs-Line](https://user-images.githubusercontent.com/49419742/71208006-5cab6880-2265-11ea-8228-a16cfabc1969.png)

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
