### ISSUE TITLE
Demos/ has a tar file not source as I'd expect

### ISSUE THREAD

**Issue by paul-hammant** [vincenzopalazzo/material-ui-swing#94]
https://github.com/vincenzopalazzo/material-ui-swing/tree/v1.1.1-beta/demos
  - Demo-Swing-set3.tar

Is the source for Demo-Swing-set3.tar somewhere else ?

**Comment by vincenzopalazzo** [comment]
Hi @paul-hammant 

Yes, the Demo is a separate repository, you can find [it here](https://github.com/vincenzopalazzo/setSwing3)

PS: I'm releasing the last code of the demo inside the repository, but the support of the demo is incomplete.

Thanks for your time in the valuation material-ui-swing library.

**Comment by vincenzopalazzo** [comment]
Marked this how fixed :smile:
