### ISSUE TITLE
Is there any way to use the default jtoggle button (the one without icon) - Not an issue

### ISSUE THREAD

**Issue by MJ-DEV91** [vincenzopalazzo/material-ui-swing#95]
Hello.
I realized that you used a custom JToggleButton and it's really cool, but I'm wondering is there any way to use a JToggleButton just like the default one? I mean, I don't want to use an icon for JToggleButton and I'm not sure where should I change to accomplish that. Can you please help me in this regard?

**Comment by vincenzopalazzo** [comment]
Hi @MJ-DEV91,

>it's really cool

Thanks! :smile:

>Can you please help me in this regard?

Absolutely yes, so there is some solution for this, like MaterialTheming or a personal ToggleUI.

## MeterialTheming 

With MaterialTheming you can change the icon to the toggle button, or you can set se icon null, like this:

```

package mdlaf;

import mdlaf.themes.JMarsDarkTheme;

/**
 * @author https://github.com/vincenzopalazzo
 */
public class PersonalToggleButtonTheme extends JMarsDarkTheme {

    @Override
    protected void installIcons() {
        super.installIcons();

        this.unselectedIconToggleButton = null;
        this.selectedIconToggleButton = null;
    }
}
```
the effect is this, without icon, with only label.

![Selection_085](https://user-images.githubusercontent.com/17150045/71591304-28209200-2b2c-11ea-8d58-5b407af774dc.png)

## You can load the Another JToggleButtonUI from UIManager, with this code inside your main.

```
static {
        UIManager.put("ToggleButtonUI", MetalToggleButtonUI.class.getCanonicalName());
    }
```
This code have this effect in this cases

![Selection_086](https://user-images.githubusercontent.com/17150045/71591452-ab41e800-2b2c-11ea-9108-83fba569bfc3.png)

## Conclusion

I think the second point is the solution that you are finding, but if you have any proposals you can describe here and I will try to help you.

Thanks for using the material-ui-swing library

**Comment by MJ-DEV91** [comment]
Thank you so much. Actually, the second solution is better for me, but it would be great if the toggle button looks like the theme, is there any way to do that? The first one is a little weird because the toggle button becomes just a label!

**Comment by vincenzopalazzo** [comment]
Hi @MJ-DEV91, 

I will try to implement the new style of the JToggleButton when the Icons are null, but I will have to need an example of the style.

I can try to support this effect ![](https://storage.googleapis.com/spec-host-backup/mio-components%2Fassets%2F1ual-GXUAsETAGunFrTagJhSnyCfYH3dD%2Ftoggle-buttons-states.png) but I don't know at the moment if this is possible (Is not possible have the Focus and Pressed effect); I will work on.

**Comment by MJ-DEV91** [comment]
It seems that the new toggle button has been added. Could you please show an example of how to use that?

**Comment by vincenzopalazzo** [comment]
Hi @MJ-DEV91,

Yes, I have released the second style of JToggleButton yesterday, you can enable the second style with the MaterialTheming.

You can implement the new theme, like [this](https://github.com/vincenzopalazzo/material-ui-swing/blob/development/src/test/java/integration/gui/mock/PersonalToggleButtonTheme.java) and you can set it how new theme material-ui.swing, with code like this

https://github.com/vincenzopalazzo/material-ui-swing/blob/31ab2b857b66d939cadbac843c8dd4be6c2ddcf9/src/test/java/integration/gui/mock/DemoGUITest.java#L46-L55

Override the JMarsTheme with PersonalToggleButtonTheme.

More details are described [here](https://github.com/vincenzopalazzo/material-ui-swing/blob/development/docs/CHANGELOG.md)

PS: The style si implemented inside the development branch, you can clone it and create the new jar for test the new version inside your project or you can run the demo test inside the project, so [this](https://github.com/vincenzopalazzo/material-ui-swing/blob/development/src/test/java/integration/gui/mock/DemoGUITest.java)

also, I want to add the possibility to choose the style of the ToggleButton, I want to create a method where the developer can use the two styles together

I will attend your feedback, see you soon :smile:

**Comment by vincenzopalazzo** [comment]
Fixed in https://github.com/vincenzopalazzo/material-ui-swing/releases/tag/v1.1.1-prelease
